### ISSUE TITLE
Currently available public DNS-over-QUIC upstreams list.

### ISSUE THREAD

**Issue by hongyi-zhao** [AdguardTeam/dnsproxy#101]
Hi,

I noticed that dnsproxy DNS-over-QUIC upstream, but still I can't find any public list for DNS-over-QUIC upstreams.

Any hints?

Regards,
HY

**Comment by ameshkov** [comment]
Note that it's experimental and unstable.

There're only three that I know:)

* `quic://dns.adguard.com`
* `quic://dns-unfiltered.adguard.com`
* `quic://dns-family.adguard.com`

**Comment by hongyi-zhao** [comment]
All are supplied by adguard.

**Comment by ameshkov** [comment]
True. But note that you can use dnsproxy and run your own DOQ resolver.

**Comment by hongyi-zhao** [comment]
> True. But note that you can use dnsproxy and run your own DOQ resolver.

What do you mean by saying that **run your own DOQ resolver**? If you mean that I can setup a DOQ resolver as my own server, then what's the tool for me to to the job?

Regards,
HY

**Comment by ameshkov** [comment]
Check this repo readme, dnsproxy can work as a DoQ server as well

**Comment by hongyi-zhao** [comment]
Yes, I've previously noticed the following example shown [here](https://github.com/AdguardTeam/dnsproxy#encrypted-dns-server).

```
Runs a DNS-over-QUIC proxy on 127.0.0.1:784.
./dnsproxy -l 127.0.0.1 --quic-port=784 --tls-crt=example.crt --tls-key=example.key -u 8.8.8.8:53 -p 0
```

But I still have some questions on this usage:

1. How to prepare the example.crt and example.key files required by the above command?
2. In this case, the upstream is a plain DNS, i.e., 8.8.8.8:53, which is poisoned for my location. So, I think it's useless for me to make a DNS-over-QUIC server/resolver based on some already poisoned upstream forwarders.
3. When I make a DNS-over-QUIC server/resolver, say, in the above example, it listens on 127.0.0.1:784, then can I use/check it with dig like the following:

`$ dig www.baidu.com -p 784 @127.0.0.1
`

**Comment by ameshkov** [comment]
> How to prepare the example.crt and example.key files required by the above command?

You need your own domain name, then just use let's encrypt.

> In this case, the upstream is a plain DNS, i.e., 8.8.8.8:53, which is poisoned for my location. So, I think it's useless for me to make a DNS-over-QUIC server/resolver based on some already poisoned upstream forwarders.

This is just an example, you can use whatever upstream you want.

> When I make a DNS-over-QUIC server/resolver, say, in the above example, it listens on 127.0.0.1:784, then can I use/check it with dig like the following:

Try dnslookup:
https://github.com/ameshkov/dnslookup

**Comment by hongyi-zhao** [comment]
> > How to prepare the example.crt and example.key files required by the above command?
> 
> You need your own domain name, then just use let's encrypt.

I must first have a domain name. But still can't figure out the meaning saying by you: __just use let's encrypt__. Any more hints?

> 
> > In this case, the upstream is a plain DNS, i.e., 8.8.8.8:53, which is poisoned for my location. So, I think it's useless for me to make a DNS-over-QUIC server/resolver based on some already poisoned upstream forwarders.
> 
> This is just an example, you can use whatever upstream you want.

The problem is: if the upstream itself already has the capability of anti-poisoning, then why should I bother this wrapper again?


> 
> > When I make a DNS-over-QUIC server/resolver, say, in the above example, it listens on 127.0.0.1:784, then can I use/check it with dig like the following:
> 
> Try dnslookup:
> https://github.com/ameshkov/dnslookup

**Comment by ameshkov** [comment]
> I must first have a domain name. But still can't figure out the meaning saying by you: just use let's encrypt. Any more hints?

Here's a relevant manual: https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#certificate

> The problem is: if the upstream itself already has the capability of anti-poisoning, then why should I bother this wrapper again?

I can't answer this, I am just telling you what options there are.
