### ISSUE TITLE
About the algorithm used by the --fastest-addr option.

### ISSUE THREAD

**Issue by hongyi-zhao** [AdguardTeam/dnsproxy#103]
Hi,

I noticed that dnsproxy has the following option  currently:

`
--fastest-addr    Respond to A or AAAA requests only with the fastest IP address`

But, IMO, the first returned IP address maybe not the fastest one. So, I want to know what's algorithm used by dnsproxy to determine the fastest-addr which is corresponding the option --fastest-addr?

Regards,
HY

**Comment by ameshkov** [comment]
> So, I want to know what's algorithm used by dnsproxy to determine the fastest-addr which is corresponding the option

It tries to connect to all IP addresses and returns the one that's the fastest

**Comment by hongyi-zhao** [comment]
> It tries to connect to all IP addresses and returns the one that's the fastest

The problem is: in some places, some IP addresses maybe banned the local government's firewall. As a result, the direct connect testing to these IP addresses will fail definitely.

**Comment by ameshkov** [comment]
> As a result, the direct connect testing to these IP addresses will fail definitely.

Sure, and these IP addresses definitely cannot be categorized as "fastest" in this case.

**Comment by hongyi-zhao** [comment]
The key to the question here discussed is: dnsproxy only ensure the correct IP addresses are returned, while the connection to the IP addresses maybe need via proxy. So the real speed to the IP addresses cannot be calibrated.

**Comment by ameshkov** [comment]
Well, maybe you're right, and adding socks/https proxy support won't hurt.

**Comment by hongyi-zhao** [comment]
Even you add the socks/https proxy support for **--fastest-addr** finding. The problem is still complicated. Say, the socks/https proxy itself maybe a forwarder/load-balancer/gateway which uses multiple upstream socks/https servers as the backend. In this case, the testing results of **--fastest-addr** will depends on the real-time picked out backends.

**Comment by ameshkov** [comment]
I think you're overthinking it. This feature is not mandatory, and if the proxy itself is that complicated, it simply shouldn't be used.

**Comment by terrytw** [comment]
@ameshkov Can you please clarify what you meant by "connect to all IP addresses"?
Is it a HTTP request or a ICMP request?

**Comment by ameshkov** [comment]
@terrytw it's TCP to ports 80 and 443
