### ISSUE TITLE
dnsproxy does not cache responses with CNAME RRs only

### ISSUE THREAD

**Issue by lhzw** [AdguardTeam/dnsproxy#104]
Can we cache AAAA's cname or something, it will send a request each time on a AAAA CANME even if we have cached A's result, feeling unhappy about it, it's useless and wasting time and energy. Or we just disable the ipv6 dns query?

This is from adguardhome's query log.
```
21:11:28 20/09/2020
api.waqi.info
Type: AAAA, Plain DNS
Processed
499 ms
172.20.0.1

21:11:27 20/09/2020
api.waqi.info
Type: A, Plain DNS
Processed
0.30 ms
172.20.0.1

```
Response details of the AAAA query:
```
Status         Processed
DNS server     https://8.8.8.8:443/dns-query
Elapsed        499 ms
Response code  NOERROR
Response       CNAME: jp1n.waqi.info. (ttl=6660)
```

**Comment by lhzw** [comment]
Disable ipv6 does help.

**Comment by ameshkov** [comment]
> Response       CNAME: jp1n.waqi.info. (ttl=6660)

No A or AAAA records in the response, I think this is the reason @szolin

**Comment by ameshkov** [comment]
Huh, it appears that caching responses with CNAMEs is counter-productive and we had troubles because of that before: https://github.com/AdguardTeam/dnsproxy/commit/4343ae4cb4fbf34d9a41c74dddabc6e9906e2ecb
