### ISSUE TITLE
Use the dnsproxy running on host from within docker container.

### ISSUE THREAD

**Issue by hongyi-zhao** [AdguardTeam/dnsproxy#107]
Hi,

Say, I've a docker container and at the same time, I run dnsproxy on the host as the local DNS resolver listening on 1270.0.1:6053. In this case, how should I set the iptables so that docker container can use the dnsproxy running on host?

Regards,
HY

**Comment by ameshkov** [comment]
Tbh, I am not an expert at docker and it's hard for me to answer. Maybe someone else could help you, I'll keep this issue open for now.

**Comment by natesales** [comment]
Admittedly I'm late to the party, but I'll give this a go in case you're still wondering about this.

First, create a docker network for dnsproxy:
`sudo docker network create --subnet=172.20.0.0/24 dnsproxy`

Then start dnsproxy bound to an address within that network:
`sudo ./dnsproxy -u https://cloudflare-dns.com/dns-query -b 1.1.1.1:53 -l 172.20.0.1`

And pass the `--network` and `--dns` flags to docker run:
`sudo docker run --network=dnsproxy --ip 172.20.0.2 --dns=172.20.0.1 --rm -it ubuntu /bin/bash`

The container will then use 172.20.0.1 (dnsproxy) as it's DNS server. Hope this helps!

(Reference: https://docs.docker.com/engine/reference/run/#network-settings)

**Comment by hongyi-zhao** [comment]
Thanks a lot for your instructions. I tried it exactly according to your steps and still have some other questions:

1. The content of the `/etc/resolv.conf` for the container is shown as below:
```
root@5b5956aac035:/# cat /etc/resolv.conf 
search lan
nameserver 127.0.0.11
options edns0 trust-ad ndots:0
```
As you can see, it still uses 127.0.0.11 as the default DNS server, so how can I check/ensure the DNS server assigned by `--dns=172.20.0.1` option is always used by the docker container?

2. How to let the docker container obtain an IP address on the corresponding subnet automatically without manual allocation through the `--ip 172.20.0.2` argument?

Regards,
HY

**Comment by natesales** [comment]
It depends on the container image, but ubuntu for example uses resolvconf so that will be a loopback address in `/etc/resolv.conf`, used as a forwarder to the upstream DNS server set by `--dns`.

You can verify this works by using the steps I outlined above, then install dig in the container and try a query. Now, terminate the dnscrypt process and try the query again - you'll see it time out with a `no servers could be reached` message because the dnscrypt server is no longer running.

To let docker assign an IP address automatically, just leave out the `--ip` flag in your docker run command and docker will handle the rest.

**Comment by hongyi-zhao** [comment]
I try to install the dig package first with the following steps but failed:

Start dnsproxy on host:
```
$ ./dnsproxy -u 114.114.114.114:53 -l 172.20.0.1 -p 6666
```
Then starting the container with root and try to install the dig package:
```
werner@X10DAi:~$ docker run --network=dnsproxy --ip 172.20.0.2 --dns=172.20.0.1 -u root --rm -it ubuntu /bin/bash
root@70ce73ab80fe:/# sed -i 's|archive.ubuntu.com|deb.debian.org|;s|security.ubuntu.com|deb.debian.org|' /etc/apt/sources.list
root@70ce73ab80fe:/# apt update
Err:1 http://deb.debian.org/ubuntu focal InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/ubuntu focal-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/ubuntu focal-backports InRelease
  Temporary failure resolving 'deb.debian.org'
0% [Connecting to deb.debian.org]^C
```

**Comment by natesales** [comment]
You're listening on port 6666, as per the `-p` flag. Docker is expecting the DNS server to be on port 53.

**Comment by hongyi-zhao** [comment]
> You're listening on port 6666, as per the `-p` flag. Docker is expecting the DNS server to be on port 53.

Thanks a lot for spotting my error. The following will do the trick and confirm that your method is correct:

`$ sudo ./dnsproxy -u 114.114.114.114:53 -l 172.20.0.1 -p 53 -v`

Thanks again.

Regards,
HY
