### ISSUE TITLE
bogus_nxdomain does not block responses when at least one IP address is not listed as bogus

### ISSUE THREAD

**Issue by PussAzuki** [AdguardTeam/dnsproxy#115]
1. When the "fastest address" mode is turned on, the "bogus-nxdomain" function does not seem to work.

2. In the "fastest address" mode, AGH seems to ignore the network environment: for example, after artificially blocking the IP address and confirming that it has been blocked, AGH still has the opportunity to select a blocked IP address that is inconsistent with the description in the README file.

3. I think the ping speed measurement in "fastest address" mode gives up too quickly. I personally recommend reducing the time of a single ping by referring to [smartdns](https://github.com/pymumu/smartdns/), but the number of times is increased to twice. in my case, it takes very little time to test ping, but sometimes it takes a long time.

**Comment by PussAzuki** [comment]
Bug example

AdguardTeam/AdGuardHome#2394

**Comment by ameshkov** [comment]
> When the "fastest address" mode is turned on, the "bogus-nxdomain" function does not seem to work.

I cannot reproduce this.

> for example, after artificially blocking the IP address and confirming that it has been blocked

I cannot reproduce this either. Have you completely blocked an IP or just blocked one of the ports?

Because here's what I see in your log:

![image](https://user-images.githubusercontent.com/5947035/101680620-02a54380-3a72-11eb-8bd8-524684e6a404.png)

**Comment by PussAzuki** [comment]
For the first problem you say can't be repeated: it does happen, but it can't happen 100%.

For the second question, I think this is also a bug. 
[ping&tcping test](https://i.loli.net/2020/12/10/BWiMdFTOklnGHox.png) [AGH log output](https://i.loli.net/2020/12/10/dxumoMkp95QHPWY.png)
If you think I only blocked 443 but not port 80, then this will not be the result.

**Comment by PussAzuki** [comment]
The first problem is that there will be an error when replacing a new cache only after a cache time has expired.

Ping should not be a feature of connectivity, because some websites do block ping, then at that time, it is normal for ping to return failure. So I think if you really want to do ping, you should lower the single timeout threshold, and then increase the number of tests. It is really lack of reference to do ping only once.

**Comment by ameshkov** [comment]
> If you think I only blocked 443 but not port 80, then this will not be the result.

Try `telnet IPADDRESS 80` and see if it gets connected.

From the log, it seems that port 80 is reachable.

> Ping should not be a feature of connectivity, because some websites do block ping, then at that time, it is normal for ping to return failure. So I think if you really want to do ping, you should lower the single timeout threshold, and then increase the number of tests. It is really lack of reference to do ping only once.

This way checking if IP address is alive would take too long.

What SmartDNS does to solve this?

**Comment by PussAzuki** [comment]
[telnet IPADDRESS 80 results](https://i.loli.net/2020/12/10/136h8kNCoFJSyLe.png)
I tried it, but it was blocked too.

I think ping can only confirm whether the server supports the ping command, so it should be optional rather than required

SmartDNS seems to limit the time it takes to return results from the server, and I don't know exactly what to do, but there will also be a DNS request timeout when using ping on smartdns to measure speed. So I think it is more reasonable to use tcp to detect ports 443 and 80 first.

**Comment by ameshkov** [comment]
> So I think it is more reasonable to use tcp to detect ports 443 and 80 first.

This is exactly what we're doing.

Please note, AGH does not do pings.

**Comment by PussAzuki** [comment]
But I see the ping timeout [here](https://github.com/AdguardTeam/dnsproxy/blob/master/fastip/ping.go)?

There is no denying that I can't program, so I just looked up the keywords and found the above. Please forgive me if there are any mistakes.

**Comment by ameshkov** [comment]
It's just a name:) If you look into the code, you'll see that it actually tries to establish TCP connections.

**Comment by PussAzuki** [comment]
So the problem now is that one or more IP addresses are blocked on my side, but can AGH still connect to the blocked IP addresses?

Could it be the bug in the dependency used?

**Comment by ameshkov** [comment]
I am pretty sure something is wrong with the way you're blocking these IPs.

Maybe they're blocked just for your Windows user, but AGH bypasses it as it works under system.

**Comment by PussAzuki** [comment]
It seems that I only blocked part of the connection. Now I use iptables to discard the connection from wan to the destination, and see if there will be any exceptions after a while.

**Comment by PussAzuki** [comment]
After processing, it runs slowly, slower than before, but there is no high load and full load in htop.

**Comment by PussAzuki** [comment]
Now, 2 and 3 are problems that I haven't dealt with well on my side, but the problems mentioned in 1 do exist here. Now it even returns no valid address like [this](https://i.loli.net/2020/12/10/kujrnIM2hPEW4Yz.png) and then some of the IP addresses of CDN in my country will not be found, but in the case of DNS in the upper reaches of the country. The following is [a comparative picture](https://i.loli.net/2020/12/10/X6eTcnGqagiNPsE.png)

**Comment by ameshkov** [comment]
Could you please copy/paste the relevant part of the log?

I'd also need to know what is the expected result.

**Comment by PussAzuki** [comment]
I'm sorry I can't offer more, because log is so mixed. I hope the log created by AGH should help.

您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/19ecfa7d9f4945 或进入 cowtransfer.com 获取，在首页输入取件码：103484（24小时内有效）

**Comment by PussAzuki** [comment]
Here comes the interesting part. I'm sure I can connect to this site because it's a CDN node on my side, but why do tcp connections time out?

[WTF](https://i.loli.net/2020/12/11/XB9WkF2GxCy7QfM.jpg)

[real ping test](https://i.loli.net/2020/12/11/KRrnXvDixYLp5N4.jpg)

**Comment by PussAzuki** [comment]
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11747 [debug] pingDoTCP: avatars1.githubusercontent.com.: connecting to 151.101.108.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11732 [debug] pingDoTCP: avatars1.githubusercontent.com.: connecting to 151.101.192.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11731 [debug] pingDoTCP: avatars1.githubusercontent.com.: connecting to 151.101.128.133:443
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11733 [debug] pingDoTCP: avatars1.githubusercontent.com.: connecting to 151.101.192.133:443
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11730 [debug] pingDoTCP: avatars1.githubusercontent.com.: connecting to 151.101.128.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11719 [debug] pingDoTCP: avatars3.githubusercontent.com.: failed to connect to 151.101.0.133:443, elapsed 10 ms: dial tcp 151.101.0.133:443: connect: connection refused
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11748 [debug] pingDoTCP: avatars1.githubusercontent.com.: failed to connect to 151.101.108.133:443, elapsed 11 ms: dial tcp 151.101.108.133:443: connect: connection refused
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11713 [debug] pingDoTCP: avatars1.githubusercontent.com.: connecting to 151.101.64.133:443
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11734 [debug] pingDoTCP: avatars1.githubusercontent.com.: connecting to 151.101.108.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11653 [debug] pingAll: avatars3.githubusercontent.com.: got result for 151.101.0.133 status false
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11690 [debug] pingDoTCP: avatars1.githubusercontent.com.: failed to connect to 151.101.228.133:443, elapsed 11 ms: dial tcp 151.101.228.133:443: connect: connection refused
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11735 [debug] pingDoTCP: avatars1.githubusercontent.com.: failed to connect to 151.101.108.133:443, elapsed 13 ms: dial tcp 151.101.108.133:443: connect: connection refused
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11709 [debug] pingDoTCP: avatars1.githubusercontent.com.: failed to connect to 151.101.228.133:443, elapsed 11 ms: dial tcp 151.101.228.133:443: connect: connection refused
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11623 [debug] pingAll: avatars1.githubusercontent.com.: got result for 151.101.108.133 status false
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11715 [debug] pingDoTCP: avatars3.githubusercontent.com.: failed to connect to 151.101.228.133:443, elapsed 11 ms: dial tcp 151.101.228.133:443: connect: connection refused
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11622 [debug] pingAll: avatars1.githubusercontent.com.: got result for 151.101.108.133 status false
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11623 [debug] pingAll: avatars1.githubusercontent.com.: got result for 151.101.228.133 status false
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11692 [debug] pingDoTCP: avatars1.githubusercontent.com.: failed to connect to 151.101.0.133:443, elapsed 11 ms: dial tcp 151.101.0.133:443: connect: connection refused
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11653 [debug] pingAll: avatars3.githubusercontent.com.: got result for 151.101.228.133 status false
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11622 [debug] pingAll: avatars1.githubusercontent.com.: got result for 151.101.228.133 status false
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11711 [debug] pingDoTCP: avatars1.githubusercontent.com.: failed to connect to 151.101.0.133:443, elapsed 11 ms: dial tcp 151.101.0.133:443: connect: connection refused
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11623 [debug] pingAll: avatars1.githubusercontent.com.: got result for 151.101.0.133 status false
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11622 [debug] pingAll: avatars1.githubusercontent.com.: got result for 151.101.0.133 status false
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11664 [debug] https://dns.pub:443/dns-query: response: ok
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11795 [debug] pingDoTCP: avatars3.githubusercontent.com.: connecting to 151.101.192.133:443
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11718 [debug] pingDoTCP: avatars3.githubusercontent.com.: elapsed 43 ms on 151.101.0.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11744 [debug] pingDoTCP: avatars3.githubusercontent.com.: connecting to 151.101.128.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11723 [debug] pingDoTCP: avatars3.githubusercontent.com.: elapsed 41 ms on 151.101.128.133:443
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11742 [debug] pingDoTCP: avatars3.githubusercontent.com.: connecting to 151.101.64.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11745 [debug] pingDoTCP: avatars3.githubusercontent.com.: connecting to 151.101.128.133:443
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11794 [debug] pingDoTCP: avatars3.githubusercontent.com.: connecting to 151.101.192.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11743 [debug] pingDoTCP: avatars3.githubusercontent.com.: connecting to 151.101.64.133:443
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11722 [debug] pingDoTCP: avatars3.githubusercontent.com.: elapsed 43 ms on 151.101.128.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11730 [debug] pingDoTCP: avatars1.githubusercontent.com.: elapsed 44 ms on 151.101.128.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11653 [debug] pingAll: avatars3.githubusercontent.com.: got result for 151.101.0.133 status true
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11746 [debug] pingDoTCP: avatars1.githubusercontent.com.: elapsed 48 ms on 151.101.192.133:443
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11691 [debug] pingDoTCP: avatars1.githubusercontent.com.: elapsed 56 ms on 151.101.0.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11653 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 349 ms
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11720 [debug] pingDoTCP: avatars3.githubusercontent.com.: elapsed 58 ms on 151.101.192.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11653 [debug] DNSFwd: Checking CNAME github.map.fastly.net. for avatars3.githubusercontent.com.
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11623 [debug] pingAll: avatars1.githubusercontent.com.: got result for 151.101.192.133 status true
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11733 [debug] pingDoTCP: avatars1.githubusercontent.com.: elapsed 48 ms on 151.101.192.133:443
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11693 [debug] pingDoTCP: avatars1.githubusercontent.com.: elapsed 49 ms on 151.101.64.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11721 [debug] pingDoTCP: avatars3.githubusercontent.com.: elapsed 54 ms on 151.101.192.133:443
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11734 [debug] pingDoTCP: avatars1.githubusercontent.com.: elapsed 48 ms on 151.101.108.133:80
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11653 [debug] DNSFwd: Checking record A (151.101.0.133) for github.map.fastly.net.
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11623 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 343 ms
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11622 [debug] pingAll: avatars1.githubusercontent.com.: got result for 151.101.128.133 status true
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: 2020/12/10 20:39:23 3136#11653 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 9977
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]:
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: ;; QUESTION SECTION:
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: ;avatars3.githubusercontent.com.	IN	 A
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]:
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: ;; ANSWER SECTION:
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: avatars3.githubusercontent.com.	428	IN	CNAME	github.map.fastly.net.
Fri Dec 11 04:39:23 2020 daemon.err AdGuardHome[3136]: github.map.fastly.net.	29	IN	A	151.101.0.133

**Comment by PussAzuki** [comment]
This time, I do not block the IPs but add these IPs to nxdomain list. And sometimes it just not work.

**Comment by ameshkov** [comment]
> Here comes the interesting part. I'm sure I can connect to this site because it's a CDN node on my side, but why do tcp connections time out?

Try using `tcpping` or `telnet` to do the test, don't use simple `ping` - it's a different thing and the result does not show anything.

> but add these IPs to nxdomain list

What list is it?

**Comment by PussAzuki** [comment]
1. I have used "iptables -I zone_wan_output -d 151.101.0.133 -j DROP" & "iptables -I zone_wan_output -d 151.101.228.133 -j DROP" to drop the packet from the exit of the wan and confirm that the router cannot be connected to the IPs. But these CDN IP and I are in Chinese mainland, why do I still see their timeout in AGH's log?

2. I think this is the right way to use it? [shortcut](https://i.loli.net/2020/12/15/Q9D6wkaEYNlSWyC.png)

**Comment by ameshkov** [comment]
Okay, there's one more thing about how `bogux_nxdomain` works in dnsproxy/AdGuard Home, **ALL IP ADDRESSES** in the response should be bogus.

Could it be that this is what's causing your issue?
Would you like it to work differently?

**Comment by PussAzuki** [comment]
Maybe, in my opinion, there are some injustices in the current method: for example, the uncontaminated IP will be mistakenly treated as the same part of the contaminated part, which will lead to the current problem. It may be better to change it to IP blacklist and whitelist, at least several of the ones I've seen are blacklist domain name matching + forced filtering of specific upstream IP whitelist to deal with this part of the problem.

And then I thought it was an IP blacklist function instead of what it is now.

**Comment by ameshkov** [comment]
The point of adding `bogus_nxdomain` was to make dnsproxy and AGH compatible with dnsmasq lists with `bogus-nxdomain` popular among Chinese users. That's why it's important to work just like dnsmasq does.

Regarding IP blacklist/whitelist, are there any lists of such IPs I can take a look at?

**Comment by PussAzuki** [comment]
I think bogus_nxdomain may be very easy to use, as long as you understand the usage, but the fastest IP mode function that attracts Chinese users.

Yes, there is an IP whitelist, for example, "chnroute" is the CIDR, of all the IPv4 addresses of Chinese mainland, and "chnroute6" is on IPv6. Generally speaking, they can be generated like this.  `curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > chnroute.txt`

Banip provides another way `https://stat.ripe.net/data/country-resource-list/data.json?resource=` Fill in the country name or ASN number after it. and I prefer this way.

I think the IP blacklist and whitelist based on the upstream of DNS can better protect the privacy of DNS, because it can prevent the generation of query records based on IP address to a great extent. But I don't think excessive use of IP blacklist and whitelist can protect more privacy. So I think only one black and white list is needed.

Finally, I think it is best to add a DNS upstream grouping function. Even if the rules can be written a lot, and you can also use tools to copy and paste in batches, but I think it can reduce the amount of unnecessary data and greatly reduce the consumption of resources.

**Comment by ameshkov** [comment]
Well, IP whitelist/blacklist should be a separate feature request, and it's closely tied with the "fastest IP addr" mode. So basically, you'd like to be able to set a list of CIDR ranges that are "whitelisted", all others should be simply discarded from DNS responses, right?

Meanwhile, I've verified that our behavior for `bogus_nxdomain` is indeed different from dnsmasq, and I guess we should fix this.

**Comment by PussAzuki** [comment]
It is true that the IP blacklist and whitelist should be a separate and upstream feature based on each separate DNS. But it should never be bound to the fastest IP schema, because IP blacklist/whitelist should be two optional functions.
The later part of the description is my idea. If necessary, you can refer to [overture](https://github.com/shawn1m/overture), which also uses the go language, but I don't use it because it really eats too much performance. 
If possible, use efficient ipset to implement the IP blacklist and whitelist, which is used by many C/C++ based projects to achieve the same goal.

Finally, can I have a feature that groups each individual DNS upstream, or called custom abbreviations? Nothing else, but because of lazy.😶

**Comment by ameshkov** [comment]
Well, could you please file both feature requests and we'll see how many upvotes they'll get.

I suggest filing them to AdGuard Home repo, though.
