### ISSUE TITLE
dnsproxy+windows 10

### ISSUE THREAD

**Issue by Denirvan** [AdguardTeam/dnsproxy#118]
Hello, sorry for the newbie's question, how can I run dnsproxy on windows 10? Is there any shell for launching?

**Comment by ameshkov** [comment]
Well, just grab the Windows distr from the release page: https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.33.7

Unpack and run `dnscrypt.exe`,

**Comment by Denirvan** [comment]
Андрей здравствуйте, я раньше скачивал файл dnsproxy-windows-amd64-v0.33.7.zip, но сам файл запуска dnsproxy.exe как бы не активный и не запускается, как я понимаю для него нужна оболочка?

**Comment by ameshkov** [comment]
@Denirvan вам надо запустить `cmd.exe` и уже из консоли запускать dnsproxy: https://sonikelf.ru/vvodnaya-statya-po-rabote-v-konsoli-chto-takoe-konsol-komandy-konsoli-i-prochee-takoe-raznoe-cmd/#:~:text=%D0%A7%D1%82%D0%BE%D0%B1%D1%8B%20%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D1%82%D0%B8%D1%82%D1%8C%20%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D1%83%D1%8E%20%D1%81%D1%82%D1%80%D0%BE%D0%BA%D1%83%2C%20%D0%BD%D0%B0%D0%B6%D0%BC%D0%B8%D1%82%D0%B5,%D0%9A%D0%B0%D0%BA%20%D0%B2%D0%B8%D0%B4%D0%B8%D1%82%D0%B5%2C%20%D0%B2%D1%81%D0%B5%20%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D1%82%D0%BE%D1%87%D0%BD%D0%BE%20%D0%B0%D1%81%D0%BA%D0%B5%D1%82%D0%B8%D1%87%D0%BD%D0%BE.

**Comment by Denirvan** [comment]
Я вас понял, я думал что есть оболочка с настройками, например такая как Simple DNSCrypt.
