### ISSUE TITLE
IPV6 first command

### ISSUE THREAD

**Issue by Macqael** [AdguardTeam/dnsproxy#124]
Hello i use this service for some time, but in my network log it connect 90% of the time with ipv4 is there a possibility to add a way (i don't have seen one in readme.md) to add somting like --use-ipv6 or something like that to "force" dnsproxy to ask the AAAA adresses of the DOH/DOT/QUIC and if fail, fallback to ipv4 ?

Because like i said my network is fully ipv6 enabled and only the network who use dnsproxy use ipv4 for communicate to my DOH/DOT/QUIC server.

**Comment by ameshkov** [comment]
The thing is that it does not work that way.

Your clients (OS, browsers) ask for both IPv4 and IPv6 in two different DNS queries (type A and type AAAA) and it's up to them to decide which one is preferred.

**Comment by Macqael** [comment]
@ameshkov i was not talking about resolving by the browser to the dnproxy, but the dnsproxy itself who contact my ADH server by ipv4 even if my ipv6 is here, i want a way to tell dnsproxy, contact the upstream server by ipv6 only and if it's fail come back to ipv4.
