### ISSUE TITLE
DNSProxy uses encrypted domain name DNS. After the other party changes the IP, the program cannot automatically obtain the new IP.

### ISSUE THREAD

**Issue by tudnew** [AdguardTeam/dnsproxy#125]
The IP could not be obtained normally this morning. The check is that the DNS server IP has changed, and DNSProxy did not use -b to obtain the new IP again, and kept trying to resolve with the old IP.
The startup configuration is dnsproxy.exe -u quic://xx.cc -b 223.5.5.5, and it is normal after restarting the program.
I have not opened the log, so I cannot provide it..........
English is not good, the following is the original text.

DNSProxy 用加密域名DNS，对方变动了IP后程序无法自动获取新的IP。
今天早上无法正常获取IP，检查为DNS服务器IP变动了，而DNSProxy没有重新用-b获取新的IP，一直用旧IP尝试解析。
启动配置为 dnsproxy.exe -u quic://xx.cc -b 223.5.5.5，重启程序后正常。
我没有开启日志，所以无法提供..........

**Comment by ameshkov** [comment]
dnsproxy 不更新 DNS 服务器的 IP 地址。dnsproxy 开启的时候解析 DNS 服务器，然后一直用它。

唯一的办法是你写一条脚本定期检查 DNS 服务器的 IP 地址，一改变了，就重启 dnsproxy。
