### ISSUE TITLE
DNS-over-QUIC draft-ietf-dprive-dnsoquic-02 implementation

### ISSUE THREAD

**Issue by natesales** [AdguardTeam/dnsproxy#127]
Last week, the IETF released [a new draft](https://datatracker.ietf.org/doc/html/draft-ietf-dprive-dnsoquic-02) of DNS-over-QUIC. I've implemented the draft with backwards compatibility for the current dnsproxy DoQ draft (draft-ietf-dprive-dnsoquic-00) in https://github.com/natesales/dnsproxy/tree/doq-02.

Is this something I should open a PR for? I wanted to check in here beforehand, given it's a protocol change.

**Comment by ameshkov** [comment]
Thank you! Please open a pull request, I guess it'd be easier to discuss the changes this way anyway.

**Comment by natesales** [comment]
Merged in https://github.com/AdguardTeam/dnsproxy/pull/128

**Comment by ameshkov** [comment]
@natesales I've added some changes on top of you PR, please take a look just in case: https://github.com/AdguardTeam/dnsproxy/blob/master/upstream/upstream_quic.go#L53

**Comment by natesales** [comment]
Thanks, that's a nice way to do it so the ID can be sent upstream as zero but returned as original. Looks good to me.
