### ISSUE TITLE
Responses from cache don't get truncated

### ISSUE THREAD

**Issue by mnordhoff** [AdguardTeam/dnsproxy#131]
If caching is disabled, or if there was a cache miss, dnsproxy will truncate the response if appropriate. When there's a cache hit, it will return a large response even if it exceeds the request's EDNS payload size (or the default 512 if it didn't use EDNS).

To reproduce:

1. Run "`./dnsproxy -p 1053 -u tls://dns.adguard.com --cache`".
2. Run "`dig +ignore -p 1053 locations.publicdns.goog txt`". The response will be truncated.
3. Run "`dig +ignore -p 1053 locations.publicdns.goog txt`" again. You'll get the full, 5 KB response.

I guess it's because, in `Resolve`, cache hits return here:

https://github.com/AdguardTeam/dnsproxy/blob/200e1aa9914c0172d5642aa405fbc896fb403f9e/proxy/proxy.go#L413-L418

But truncation is handled later:

https://github.com/AdguardTeam/dnsproxy/blob/200e1aa9914c0172d5642aa405fbc896fb403f9e/proxy/proxy.go#L484-L485

(Hello again!)

**Comment by mnordhoff** [comment]
@EugeneOne1 I hope it's not creepy of me to comment on a branch that isn't even part of a PR yet, but regarding

https://github.com/AdguardTeam/dnsproxy/blob/247c0aa9591438b6dce61b0883fee3fbffa6f715/proxy/dns_context.go#L100

I'm not sure what all the effects of this are\*, but EDNS is useful on other Rcodes.

* RcodeNameError - DNSSEC NXDOMAIN responses are often larger than 512 bytes, and downstream clients may want the `DO` bit and DNSSEC records.
* RcodeServerFailure - [RFC 8914 Extended DNS Errors](https://www.rfc-editor.org/rfc/rfc8914.html) are cool. Though I don't know if anything uses them yet except me examining my own logs. :D    
* RcodeFormatError - Apparently [EDNS uses FormError with EDNS](https://tools.ietf.org/html/rfc6891#section-7) to indicate that the client sent an invalid OPT record.

It might also confuse some downstream clients (maybe systemd-resolved with DNSSEC validation? I don't know) if dnsproxy seemingly turns EDNS support on and off.

There might be cases where it's bad to have EDNS, but there are also cases where it's good. (And a lot of cases where it doesn't matter.)

\* If it happens before truncation, it would cause responses to be truncated at 512 bytes? If it happens after truncation, it could cause large UDP responses to be sent without EDNS, which would be invalid?

**Comment by EugeneOne1** [comment]
Well, this issue (and also #132) should be fixed as of v0.35.5.  Could you please check, if our solution makes `dnsproxy` work fine for you?

**Comment by mnordhoff** [comment]
It works for me, I think. :D

**Comment by EugeneOne1** [comment]
So, I'm gonna close both issues for now.  Thanks again!
