### ISSUE TITLE
dnscrypt don't work on router

### ISSUE THREAD

**Issue by valeramalko** [AdguardTeam/dnsproxy#136]
hello, I am using the first version dnscrypt on my router, stopped working with adguard addresses.
addresses are used from a file (file attached) 
site ip addresses are not resolvable 

in log:
```
Apr  6 14:29:50 dnscrypt-proxy[1134]: Unable to retrieve server certificates
Apr  6 14:29:51 dnscrypt-proxy[1134]: Refetching server certificates
```
[dnscrypt-resolvers.zip](https://github.com/AdguardTeam/dnsproxy/files/6265108/dnscrypt-resolvers.zip)

**Comment by ameshkov** [comment]
Hmm, the first version you say. 

@valeramalko could you please share this dnscrypt-proxy version? Where did you get it from? Ideally, with the source code.

**Comment by valeramalko** [comment]
@ameshkov I used dnscrypt, which builds along with the firmware from here: https://gitlab.com/dm38/padavan-ng/-/tree/master/trunk/user/dnscrypt-proxy

also checking with the package from the entware repository  http://bin.entware.net/mipselsf-k3.4/

**Comment by ameshkov** [comment]
The error seems really weird: `Unable to retrieve server certificates `

This could happen if the DNS lookup for the server cert failed, but it works okay in my case:
```
% dig -p 5443 -t txt 2.dnscrypt.family.ns1.adguard.com @176.103.130.132

; <<>> DiG 9.16.11 <<>> -p 5443 -t txt 2.dnscrypt.family.ns1.adguard.com @176.103.130.132
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41450
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;2.dnscrypt.family.ns1.adguard.com. IN	TXT

;; ANSWER SECTION:
2.dnscrypt.family.ns1.adguard.com. 60 IN TXT	"DNSC\000\001\000\000\175\244H\1357\201\203\00106\217\171\003/Q\165\028w'\211R}\"Sd}\1590\223\177\144.\144\164hz\166<l\143.+ b\201#\008\005M;\245\142\155.\013?\206\253\221\017mx\192\015e\025\218\213i\215\230\177\193\177\148\175\205\011\178\0209\146G\203\255\205\132\140\009\014\".\211\229XA\000\000\000\000\000\000\000\000`u\1288`u\1288bV\179\184"

;; Query time: 53 msec
;; SERVER: 176.103.130.132#5443(176.103.130.132)
;; WHEN: Wed Apr 14 16:26:03 MSK 2021
;; MSG SIZE  rcvd: 221
```

**Comment by valeramalko** [comment]
when adguard is specified as a resolver in the router settings, from the router: 
```
/opt/home/admin # dig @127.0.0.1 ya.ru

; <<>> DiG 9.17.10 <<>> @127.0.0.1 ya.ru
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

when another dns (not adguard) is specified as a resolver in the router settings, from the router: 
```
/opt/home/admin # dig @127.0.0.1 ya.ru

; <<>> DiG 9.17.10 <<>> @127.0.0.1 ya.ru
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51074
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ya.ru.                         IN      A

;; ANSWER SECTION:
ya.ru.                  479     IN      A       87.250.250.242

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1) (UDP)
;; WHEN: Wed Apr 14 14:31:24 UTC 2021
;; MSG SIZE  rcvd: 50
```
what else can I check?

**Comment by valeramalko** [comment]
Have you recently had a certificate renewal?

**Comment by valeramalko** [comment]
Have you recently renewed your certificate?

**Comment by ameshkov** [comment]
@valeramalko I think I figured it out. Check it again in 20-30 minutes plz, it should work okay.

Also, please note that you're using old IP addresses, you'd better use `94.140.*` (look for them on the website).
