### ISSUE TITLE
Would it be an idea to have "--fastest-addr" return all IP-Addresses but in order of RTT?

### ISSUE THREAD

**Issue by cbuijs** [AdguardTeam/dnsproxy#139]
Just wondering if it makes sense to always return all IP-Addresses anyway, but by RTT order (lowest RTT first etc), instead of only the fastest based on RTT with the `--fastest-addr` feature.

Just in case the fastest happens to be not available and the second (third etc) one would be used by clients (apps/etc) as fall/failback.

**Comment by ameshkov** [comment]
The thing is that we return the response as soon as the first IP responds to probe connections. At this moment we don't yet know whether other addresses are alive.

Also, I am not fully sure the order will change anything, the apps are likely to use a random one.

**Comment by cbuijs** [comment]
Ah, makes sense. The pletory of apps and how they (mis)use DNS is a key factor indeed, in my experience the "first" IP seems to be used the most though, but has kind of the same effect (not using the others in some cases as well).

Also together with "only" testing port 80/443 (not criticism) makes it never 100% of course.

That said, would be nice to test somehow though ;-). Just to make sure :-).

Thanks for the (very quick) feedback/insight. Appreciated!
