### ISSUE TITLE
Support for DNS64

### ISSUE THREAD

**Issue by Chaz6** [AdguardTeam/dnsproxy#140]
It would be useful to be able to use dnsproxy as a DNS64 server, so that A records are converted to the appropriate AAAA record as per RFC 6146/6147. For example, 8.8.8.8 would be converted to 64:ff9b::808:808. My suggestion is to add an argument `--dns64` to enable this feature. An optional parameter `--dns64-prefix` could allow the use of a different prefix (e.g. `--dns-prefix=2001:db8:1234:5678:64::/96`. This would be particularly useful in combination with the official adguard upstream dns server.

**Comment by ameshkov** [comment]
Makes sense, thank you.

We even had this before in dnsproxy, but for a different purpose. Back then, we maintained a mobile version of dnsproxy and we needed this to auto-detect the DNS64 prefix.

Probably, that old code can be revived rather easily (and the auto-detection part is not needed anymore):
https://github.com/AdguardTeam/dnsproxy/blob/v0.21.0/proxy/dns64.go
https://github.com/AdguardTeam/dnsproxy/blob/v0.21.0/proxy/dns64_test.go

**Comment by Chaz6** [comment]
This is awesome, thank you!
