### ISSUE TITLE
Allow loading upstreams list from a file

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#142]
这样是无法使用？？
/root/./dnsproxy -l 0.0.0.0 -p 5353 --upstream /root/domain_full.txt --all-servers --edns &

**Comment by ameshkov** [comment]
啊，还不能用命令行设计 upstream 文件。需要吗？

**Comment by Potterli20** [comment]
🥳🥳🥳

**Comment by Potterli20** [comment]
> 啊，还不能用命令行设计 upstream 文件。需要吗？

其实我需要的的，因为我看到home是可以用文件，就想着，dnsproxy也是可以用的。

**Comment by ameshkov** [comment]
是啊，把这个功能增加到dnsproxy有意义。

**Comment by Potterli20** [comment]
> 
> 
> 是啊，把这个功能增加到dnsproxy有意义。

![图片](https://user-images.githubusercontent.com/28734349/116381323-5fe63980-a847-11eb-9e3c-d288c4d2decc.png)
![图片](https://user-images.githubusercontent.com/28734349/116381355-6674b100-a847-11eb-8523-adc7c5463aee.png)
已经·好了
