### ISSUE TITLE
这个好像写错了

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#143]
![图片](https://user-images.githubusercontent.com/28734349/117855995-aadb6480-b2bd-11eb-8e9e-9b5b0de1947e.png)

**Comment by ameshkov** [comment]
我看不懂你说的是什么问题。如果你想举报bug，应该详细的描述它。

**Comment by Potterli20** [comment]
> 
> 
> 我看不懂你说的是什么问题。如果你想举报bug，应该详细的描述它。

没有办法显示版本号

**Comment by ameshkov** [comment]
哦，这是从哪儿下载的问题？

**Comment by Potterli20** [comment]
> 
> 
> 哦，这是从哪儿下载的版本？

自己编译的 git master

**Comment by ameshkov** [comment]
啊，我懂了。那你应该用 make 编译，比如：`VERSION=dev make`

**Comment by Potterli20** [comment]
> 
> 
> 啊，我懂了。那你应该用 make 编译，比如：`VERSION=dev make`

我是用了go

**Comment by ameshkov** [comment]
看看https://github.com/AdguardTeam/dnsproxy/blob/master/Makefile#L25
