### ISSUE TITLE
0.37.5 doesn't filter EDNS or DNSSEC records from cache misses

### ISSUE THREAD

**Issue by mnordhoff** [AdguardTeam/dnsproxy#148]
0785d1c26959e9af348272159f95becd4e5ffb03 removed a call to `filterMsg` to fix #144, but I think it's causing problems for responses generated by cache misses. For example, run "`dnsproxy -l 127.0.0.1 -l ::1 -p 1053 -u tls://dns.google --cache`" and then run "`dig +noad +noedns -p 1053 example.com`" twice. The first response will incorrectly include `OPT` and `RRSIG` records.

An alternative fix for #144 would just be to have `isDNSSEC` return false for `DS` records. I think that would be **almost** entirely safe: The only time when it's necessary to filter `DS` records is when processing a referral from an **authoritative** nameserver, but dnsproxy _should_ only be talking to resolvers anyway, right?

A more complicated alternative fix might be to filter `DS` records from the authority section of responses, but not filter them from the answer section. That should handle referrals without affecting explicit queries.

**Comment by EugeneOne1** [comment]
@mnordhoff, hello!  We've just released the [new version](https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.37.6) of that should fix both this issue and #144.  The implementation is inspired by your second proposition and based on [RFC-4035](https://datatracker.ietf.org/doc/html/rfc4035#section-3.2.1).  Could you please check, if it now works correctly?
