### ISSUE TITLE
Dnsproxy replay does not support Chinese domain name, the problem can be big

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#153]
Dnsproxy replay does not support Chinese domain name, the problem can be big

https://github.com/felixonmars/dnsmasq-china-list/issues/374

**Comment by Potterli20** [comment]
同时dnsproxy可以做到实时更新上游，意思不用重启程序的

**Comment by ameshkov** [comment]
你应该代中文域名用punycode：https://en.wikipedia.org/wiki/Punycode。

**Comment by Potterli20** [comment]
> 你应该代中文域名用punycode：[https://en.wikipedia.org/wiki/Punycode。](https://en.wikipedia.org/wiki/Punycode%E3%80%82)

okkk

**Comment by Potterli20** [comment]
> 你应该代中文域名用punycode：[https://en.wikipedia.org/wiki/Punycode。](https://en.wikipedia.org/wiki/Punycode%E3%80%82)

现在还有一个问题是dns proxy的缓存TTL不生效

**Comment by ameshkov** [comment]
你为什么这样想？

**Comment by ameshkov** [comment]
```
;; ANSWER SECTION:
bing.com. 1060 IN A 13.107.21.200
bing.com. 1060 IN A 204.79.197.200
```

TTL 是 1060，怎么了？

**Comment by Potterli20** [comment]
> ```
> ;; ANSWER SECTION:
> bing.com. 1060 IN A 13.107.21.200
> bing.com. 1060 IN A 204.79.197.200
> ```
> 
> TTL 是 1060，怎么了？

 dig bing.com 

; <<>> DiG 9.17.16-1+0~20210721.60+debian10~1.gbpe02535-Debian <<>> bing.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6369
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 0f234f2bb4e6bbb37ee3d89d6108f1a900882a600608ccb1 (good)
;; QUESTION SECTION:
;bing.com.			IN	A

;; ANSWER SECTION:
bing.com.		600	IN	A	13.107.21.200
bing.com.		600	IN	A	204.79.197.200

;; Query time: 4 msec
;; SERVER: 10.13.255.1#53(10.13.255.1) (UDP)
;; WHEN: Tue Aug 03 15:35:05 CST 2021
;; MSG SIZE  rcvd: 97

**Comment by Potterli20** [comment]
> ```
> ;; ANSWER SECTION:
> bing.com. 1060 IN A 13.107.21.200
> bing.com. 1060 IN A 204.79.197.200
> ```
> 
> TTL 是 1060，怎么了？

但dns proxy好像不生效了，我已经重启过了

**Comment by ameshkov** [comment]
> 但dns proxy好像不生效了

我不懂，怎么好像？

你看，dnsproxy 通常用域名的 TTL。域名的 TTL 比 `cache-min-ttl` 少的话，dnsproxy 就代域名的 TTL 用它。

**Comment by Potterli20** [comment]
> > 但dns proxy好像不生效了
> 
> 我不懂，怎么好像？
> 
> 你看，dnsproxy 通常用域名的 TTL。域名的 TTL 比 `cache-min-ttl` 少的话，dnsproxy 就代域名的 TTL 用它。


emm，怎么说，我的上游是用文件的，然后我是看着官方给的文件进行去配置TTL，同样是600，但是我已经配置好了，也重启程序，也怕没有重启到，我又重启机器。但是我用dig bing.com 发现也在600以上的，就没有生效了。我的理想效果是在600以下的反馈

**Comment by Potterli20** [comment]
已修，md要加入--cache-optimistic 不然有很多人不知道。

**Comment by Potterli20** [comment]
抱歉，我重新开了，确实TTL是没有生效的，我已经加了--cache-optimistic，也是无效

**Comment by ameshkov** [comment]
> 但是我用dig bing.com 发现也在600以上的，就没有生效了。

我不懂，你为什么想 TTL 应该是600吗？

你重启了dnsproxy，缓存就是空的。
所以 dig bing.com 的时候，dnsproxy 先检查 bing.com 真的 TTL。
如果真的TTL 600上的，dnsproxy 以这个TTL 缓存 bing.com。
如果你想它总是用 600，你应该又配置--cache-max-ttl又配置--cache-min-ttl=。

**Comment by Potterli20** [comment]
> > 但是我用dig bing.com 发现也在600以上的，就没有生效了。
> 
> 我不懂，你为什么想 TTL 应该是600吗？
> 
> 你重启了dnsproxy，缓存就是空的。
> 所以 dig bing.com 的时候，dnsproxy 先检查 bing.com 真的 TTL。
> 如果真的TTL 600上的，dnsproxy 以这个TTL 缓存 bing.com。
> 如果你想它总是用 600，你应该又配置--cache-max-ttl又配置--cache-min-ttl=。

然后我现在又发现一些问题，主adgh辅是dnsproxy
主是53端口，辅是5353
第一次会找不到ip
第二次找到了ip
过了不久ip又找不到
主的设置，已经设置为5353上游并开启DNS优化，还是存在问题
![Screenshot_20210805-175818_Chrome](https://user-images.githubusercontent.com/28734349/128332422-ddf7c397-3f79-41f3-8988-46d1884df851.png)
