### ISSUE TITLE
如何使用dnsproxy的doh反代理

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#155]
我的dnsproxy端口为444
但是我要反代理443，但是，都是失败了
我网上找了反代理的操作，还是不行
所以请来问问

**Comment by f4nff** [comment]
`用dns proxy没有办法生成doh服务器`

确实不可以，之前就测过，不行的。

**Comment by Potterli20** [comment]
@ameshkov

**Comment by rampageX** [comment]
如果你测试过 `dnsproxy` 直接做 `DoH` 服务器是没问题的，那么 `nginx` 反代的问题不应该出现在这里, 因为如果做反代, 证书什么的应该在 `nginx` 里加载而不是 `dnsproxy` 中。

参考： 

> https://github.com/m13253/dns-over-https
> 
> https://github.com/TuxInvader/nginx-dns/blob/master/docs/nginx-dns-over-https.md

**Comment by f4nff** [comment]
dnsproxy 直接做 DoH 服务器是不行的，自己去测试。

`./dnsproxy -l 127.0.0.1 --https-port=443 --tls-crt=example.crt --tls-key=example.key -u 8.8.8.8:53 -p 0`

**Comment by rampageX** [comment]
> dnsproxy 直接做 DoH 服务器是不行的，自己去测试。
> 
> `./dnsproxy -l 127.0.0.1 --https-port=443 --tls-crt=example.crt --tls-key=example.key -u 8.8.8.8:53 -p 0`

怎么不行？有什么问题？

![2021-09-03_004826](https://user-images.githubusercontent.com/994081/131885434-7acb2ccf-d17a-41d3-bc31-c7a3c833c0bd.jpg)
![2021-09-03_005301](https://user-images.githubusercontent.com/994081/131885441-f6b716cf-4639-43f3-b0da-c115c641d78c.jpg)

**Comment by Potterli20** [comment]
> > dnsproxy 直接做 DoH 服务器是不行的，自己去测试。
> > `./dnsproxy -l 127.0.0.1 --https-port=443 --tls-crt=example.crt --tls-key=example.key -u 8.8.8.8:53 -p 0`
> 
> 怎么不行？有什么问题？
> 
> ![2021-09-03_004826](https://user-images.githubusercontent.com/994081/131885434-7acb2ccf-d17a-41d3-bc31-c7a3c833c0bd.jpg)
> ![2021-09-03_005301](https://user-images.githubusercontent.com/994081/131885441-f6b716cf-4639-43f3-b0da-c115c641d78c.jpg)

./dnsproxy -l 127.0.0.1 你加一下 -l 是不是有问题

**Comment by rampageX** [comment]
> > > dnsproxy 直接做 DoH 服务器是不行的，自己去测试。
> > > `./dnsproxy -l 127.0.0.1 --https-port=443 --tls-crt=example.crt --tls-key=example.key -u 8.8.8.8:53 -p 0`
> > 
> > 
> > 怎么不行？有什么问题？
> > ![2021-09-03_004826](https://user-images.githubusercontent.com/994081/131885434-7acb2ccf-d17a-41d3-bc31-c7a3c833c0bd.jpg)
> > ![2021-09-03_005301](https://user-images.githubusercontent.com/994081/131885441-f6b716cf-4639-43f3-b0da-c115c641d78c.jpg)
> 
> ./dnsproxy -l 127.0.0.1 你加一下 -l 是不是有问题

直接做 DoH 服务器不是要暴露到公网，为什么要本地监听？！你这什么逻辑？不想回答了。

**Comment by Potterli20** [comment]
> > > > dnsproxy 直接做 DoH 服务器是不行的，自己去测试。
> > > > `./dnsproxy -l 127.0.0.1 --https-port=443 --tls-crt=example.crt --tls-key=example.key -u 8.8.8.8:53 -p 0`
> > > 
> > > 
> > > 怎么不行？有什么问题？
> > > ![2021-09-03_004826](https://user-images.githubusercontent.com/994081/131885434-7acb2ccf-d17a-41d3-bc31-c7a3c833c0bd.jpg)
> > > ![2021-09-03_005301](https://user-images.githubusercontent.com/994081/131885441-f6b716cf-4639-43f3-b0da-c115c641d78c.jpg)
> > 
> > 
> > ./dnsproxy -l 127.0.0.1 你加一下 -l 是不是有问题
> 
> 直接做 DoH 服务器不是要暴露到公网，为什么要本地监听？！你这什么逻辑？不想回答了。

那我的0.0.0.0 我是0.0.0.0 也是要问题 问题在于 -l上

**Comment by f4nff** [comment]
```
dnsproxy -l 127.0.0.1 --https-port=443 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53 -p 0
2021/09/03 01:11:47 [info] Starting the DNS proxy
2021/09/03 01:11:47 [info] Starting the DNS proxy server
2021/09/03 01:11:47 [info] Creating an HTTPS server
2021/09/03 01:11:47 [info] Listening to https://127.0.0.1:443
2021/09/03 01:11:47 [info] Listening to DNS-over-HTTPS on 127.0.0.1:443
```

```
C:\Users\11>curl  -k -H "accept: application/dns-json" "https://127.0.0.1/dns-query?name=cloudflare.com&type=A"
Bad Request
```

**Comment by Potterli20** [comment]
> ```
> dnsproxy -l 127.0.0.1 --https-port=443 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53 -p 0
> 2021/09/03 01:11:47 [info] Starting the DNS proxy
> 2021/09/03 01:11:47 [info] Starting the DNS proxy server
> 2021/09/03 01:11:47 [info] Creating an HTTPS server
> 2021/09/03 01:11:47 [info] Listening to https://127.0.0.1:443
> 2021/09/03 01:11:47 [info] Listening to DNS-over-HTTPS on 127.0.0.1:443
> ```
> 
> ```
> C:\Users\11>curl  -k -H "accept: application/dns-json" "https://127.0.0.1/dns-query?name=cloudflare.com&type=A"
> Bad Request
> ```

应该是问题在于 -l上
dnsproxy  --https-port=443 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53 -p 0

你看看

**Comment by f4nff** [comment]
```
D:\go\dnsproxy>dnsproxy --https-port=443 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53
2021/09/03 01:16:24 [info] Starting the DNS proxy
2021/09/03 01:16:24 [info] Starting the DNS proxy server
2021/09/03 01:16:24 [info] Creating the UDP server socket
2021/09/03 01:16:24 [info] Listening to udp://[::]:53
2021/09/03 01:16:24 [info] Creating a TCP server socket
2021/09/03 01:16:24 [info] Listening to tcp://[::]:53
2021/09/03 01:16:24 [info] Creating an HTTPS server
2021/09/03 01:16:24 [info] Listening to https://[::]:443
2021/09/03 01:16:24 [info] Entering the UDP listener loop on [::]:53
2021/09/03 01:16:24 [info] Entering the tcp listener loop on [::]:53
2021/09/03 01:16:24 [info] Listening to DNS-over-HTTPS on [::]:443
```


```
C:\>curl  -k -H "accept: application/dns-json" "https://127.0.0.1/dns-query?name=cloudflare.com&type=A"

C:\>
```

**Comment by Potterli20** [comment]
> @Potterli20 你自己到底测没测呀，

我知道的问题，所以我在搞

**Comment by f4nff** [comment]
@Potterli20  那现在到底有没有问题呀，

**Comment by Potterli20** [comment]
> @Potterli20 那现在到底有没有问题呀，

还是有

**Comment by f4nff** [comment]
我早就发现了，
只不过都没人说，
也懒得吭声，
好像这玩意功能都没得人去测一下的。

**Comment by Potterli20** [comment]
> dnsproxy -s 443 -p 0 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53  --all-servers --edns
 
你看看

**Comment by Potterli20** [comment]
> 我早就发现了，
> 只不过都没人说，
> 也懒得吭声，
> 好像这玩意功能都没得人去测一下的。
> 
> 我之前提+socks5/http proxy
> sni host ip:port 分开自定义，都没人鸟。



> dnsproxy -s 443 -p 0 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53  --all-servers --edns
 
你看看

**Comment by Potterli20** [comment]
> 我早就发现了，
> 只不过都没人说，
> 也懒得吭声，
> 好像这玩意功能都没得人去测一下的。
> 
> 我之前提+socks5/http proxy
> sni host ip:port 分开自定义，都没人鸟。

是在-l 问题上

**Comment by rampageX** [comment]
先放证明：

![dnsproxy-doh-server](https://user-images.githubusercontent.com/994081/131890072-7bfacc87-d074-4583-98a4-42fd5866b709.jpg)
![kdig-doh-proof](https://user-images.githubusercontent.com/994081/131890090-bd8bc2e2-5b87-4ea1-84a6-b509dbbf2396.jpg)

nginx 分流设置：

```
         location /dns-query {
                proxy_pass       https://127.0.0.1:8053/dns-query;
                proxy_set_header Host      $host;
                proxy_set_header X-Real-IP $remote_addr;
        }
```

1. `dnsproxy` 独立做 DoH 没任何问题，上面已经证明；
2. `dnsproxy` + `nginx` 在 443 做 DoH 也没有任何问题，上图可以证明;
3. `dnsproxy` 在不加载证书以及密匙的情况下不会建立 HTTP 监听，这个是和其它一些 DoH 服务器一些区别，那么很简单，给它证书密匙，让它建立 HTTPS 的监听，`nginx` 相应的连接 `https://127.0.0.1:8053/dns-query` 即可。

**Comment by f4nff** [comment]
```
D:\go\dnsproxy>dnsproxy -s 443 -p 0 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53 --all-servers --edns
2021/09/03 01:36:31 [info] Starting the DNS proxy
2021/09/03 01:36:31 [info] Starting the DNS proxy server
2021/09/03 01:36:31 [info] Creating an HTTPS server
2021/09/03 01:36:31 [info] Listening to https://[::]:443
2021/09/03 01:36:31 [info] Listening to DNS-over-HTTPS on [::]:443
2021/09/03 01:37:00 [info] Stopping the DNS proxy server
2021/09/03 01:37:00 [info] Stopped the DNS proxy server

D:\go\dnsproxy>dnsproxy -l 127.0.0.1 -s 443 -p 0 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53 --all-servers --edns
2021/09/03 01:37:09 [info] Starting the DNS proxy
2021/09/03 01:37:09 [info] Starting the DNS proxy server
2021/09/03 01:37:09 [info] Creating an HTTPS server
2021/09/03 01:37:09 [info] Listening to https://127.0.0.1:443
2021/09/03 01:37:09 [info] Listening to DNS-over-HTTPS on 127.0.0.1:443
```


```
C:\Users\yy>curl  -k -H "accept: application/dns-json" "https://127.0.0.1/dns-query?name=cloudflare.com&type=A" -I
HTTP/1.1 405 Method Not Allowed
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Thu, 02 Sep 2021 17:36:45 GMT
Content-Length: 19


C:\Users\yy>curl  -k -H "accept: application/dns-json" "https://127.0.0.1/dns-query?name=cloudflare.com&type=A" -I
HTTP/1.1 405 Method Not Allowed
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Thu, 02 Sep 2021 17:37:16 GMT
Content-Length: 19
```


自己去测吧，

**Comment by Potterli20** [comment]
> ```
> D:\go\dnsproxy>dnsproxy -s 443 -p 0 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53 --all-servers --edns
> 2021/09/03 01:36:31 [info] Starting the DNS proxy
> 2021/09/03 01:36:31 [info] Starting the DNS proxy server
> 2021/09/03 01:36:31 [info] Creating an HTTPS server
> 2021/09/03 01:36:31 [info] Listening to https://[::]:443
> 2021/09/03 01:36:31 [info] Listening to DNS-over-HTTPS on [::]:443
> 2021/09/03 01:37:00 [info] Stopping the DNS proxy server
> 2021/09/03 01:37:00 [info] Stopped the DNS proxy server
> 
> D:\go\dnsproxy>dnsproxy -l 127.0.0.1 -s 443 -p 0 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53 --all-servers --edns
> 2021/09/03 01:37:09 [info] Starting the DNS proxy
> 2021/09/03 01:37:09 [info] Starting the DNS proxy server
> 2021/09/03 01:37:09 [info] Creating an HTTPS server
> 2021/09/03 01:37:09 [info] Listening to https://127.0.0.1:443
> 2021/09/03 01:37:09 [info] Listening to DNS-over-HTTPS on 127.0.0.1:443
> ```
> 
> ```
> C:\Users\yy>curl  -k -H "accept: application/dns-json" "https://127.0.0.1/dns-query?name=cloudflare.com&type=A" -I
> HTTP/1.1 405 Method Not Allowed
> Content-Type: text/plain; charset=utf-8
> X-Content-Type-Options: nosniff
> Date: Thu, 02 Sep 2021 17:36:45 GMT
> Content-Length: 19
> 
> 
> C:\Users\yy>curl  -k -H "accept: application/dns-json" "https://127.0.0.1/dns-query?name=cloudflare.com&type=A" -I
> HTTP/1.1 405 Method Not Allowed
> Content-Type: text/plain; charset=utf-8
> X-Content-Type-Options: nosniff
> Date: Thu, 02 Sep 2021 17:37:16 GMT
> Content-Length: 19
> ```
> 
> 自己去测吧，

我测了，我用了Intra测了，是可以的

**Comment by f4nff** [comment]
`1.dnsproxy 独立做 DoH 没任何问题，上面已经证明；`

为啥我不行呢？
为啥我

```
C:\Users\11>curl  -k -H "accept: application/dns-json" "https://1.0.0.1/dns-query?name=cloudflare.com&type=A"
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":true,"CD":false,"Question":[{"name":"cloudflare.com","type":1}],"Answer":[{"name":"cloudflare.com","type":1,"TTL":242,"data":"104.16.133.229"},{"name":"cloudflare.com","type":1,"TTL":242,"data":"104.16.132.229"}]}
C:\Users\11>


```

就没问题。

**Comment by f4nff** [comment]
对不起，我不会用什么玩意Intra，
dnsproxy 服务端
dnsprox 客户端

一样都不行。
这玩意用的人不多，也没人去测过。

**Comment by rampageX** [comment]
> ```
> D:\go\dnsproxy>dnsproxy -s 443 -p 0 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53 --all-servers --edns
> 2021/09/03 01:36:31 [info] Starting the DNS proxy
> 2021/09/03 01:36:31 [info] Starting the DNS proxy server
> 2021/09/03 01:36:31 [info] Creating an HTTPS server
> 2021/09/03 01:36:31 [info] Listening to https://[::]:443
> 2021/09/03 01:36:31 [info] Listening to DNS-over-HTTPS on [::]:443
> 2021/09/03 01:37:00 [info] Stopping the DNS proxy server
> 2021/09/03 01:37:00 [info] Stopped the DNS proxy server
> 
> D:\go\dnsproxy>dnsproxy -l 127.0.0.1 -s 443 -p 0 --tls-crt=1.pem --tls-key=1.key -u 192.168.2.2:53 --all-servers --edns
> 2021/09/03 01:37:09 [info] Starting the DNS proxy
> 2021/09/03 01:37:09 [info] Starting the DNS proxy server
> 2021/09/03 01:37:09 [info] Creating an HTTPS server
> 2021/09/03 01:37:09 [info] Listening to https://127.0.0.1:443
> 2021/09/03 01:37:09 [info] Listening to DNS-over-HTTPS on 127.0.0.1:443
> ```
> 
> ```
> C:\Users\yy>curl  -k -H "accept: application/dns-json" "https://127.0.0.1/dns-query?name=cloudflare.com&type=A" -I
> HTTP/1.1 405 Method Not Allowed
> Content-Type: text/plain; charset=utf-8
> X-Content-Type-Options: nosniff
> Date: Thu, 02 Sep 2021 17:36:45 GMT
> Content-Length: 19
> 
> 
> C:\Users\yy>curl  -k -H "accept: application/dns-json" "https://127.0.0.1/dns-query?name=cloudflare.com&type=A" -I
> HTTP/1.1 405 Method Not Allowed
> Content-Type: text/plain; charset=utf-8
> X-Content-Type-Options: nosniff
> Date: Thu, 02 Sep 2021 17:37:16 GMT
> Content-Length: 19
> ```
> 
> 自己去测吧，

你到底懂不懂得？你用 `application/dns-json` 去测？`json` 老早没服务器用了好吗，要用 `application/dns-message`:

curl -H 'accept: application/dns-message' 'https://dns.google/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB'  | hexdump -c

**Comment by rampageX** [comment]
> 对不起，我不会用什么玩意Intra，
> dnsproxy 服务端
> dnsproxy 客户端
> 
> 一样都不行。
> 这玩意用的人不多，也没人去测过。

真的是智商堪忧,半桶水晃得厉害

**Comment by f4nff** [comment]
没人用为啥1.0.0.1还在用，兼容性有问题。

**Comment by Potterli20** [comment]
dnsproxy,还是有兼容性有的问题

我第一次是用了`./dnsproxy -l 0.0.0.0 -v -o /root/log.txt -p 0 -s 446 --tls-crt=/root/dns/dns.crt --tls-key=/root/dns/dns.key -u 127.0.0.1:5353 --all-servers --cache --fastest-addr --refuse-any --cache-optimistic &`这个
然后看到了https://github.com/AdguardTeam/dnsproxy/issues/155#issuecomment-911912280这个图片
改为`./dnsproxy -l 0.0.0.0 -v -o /root/log.txt -p 0 -s 446 --tls-crt=/root/dns/dns.crt --tls-key=/root/dns/dns.key -u 127.0.0.1:5353 --all-servers  --edns` 就好了
是我没有研究好，我是直接用回以前的命令

**Comment by f4nff** [comment]
```
    server {

		listen 7443	ssl http2;
        server_name	dph.xyz;
		access_log	/dev/null ;
		error_log	/dev/null ;


		ssl_certificate 			../tls/dph.xyz.pem;
		ssl_certificate_key 		../tls/dph.xyz.key;
		ssl_protocols				TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
	
        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            grpc_pass grpcs://223.6.6.6:443;
			grpc_ssl_protocols TLSv1.3;
			grpc_send_timeout 60s;
			grpc_read_timeout 60s;
			grpc_next_upstream_tries 0;
			grpc_next_upstream_timeout 0;
			grpc_socket_keepalive on;
        }

	}
```

反向代理dns over https，但是nginx有bug，
grpc_socket_keepalive on; 并不生效。

**Comment by Potterli20** [comment]
> ```
>     server {
> 
> 		listen 7443	ssl http2;
>         server_name	dph.xyz;
> 		access_log	/dev/null ;
> 		error_log	/dev/null ;
> 
> 
> 		ssl_certificate 			../tls/dph.xyz.pem;
> 		ssl_certificate_key 		../tls/dph.xyz.key;
> 		ssl_protocols				TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
> 	
>         #charset koi8-r;
> 
>         #access_log  logs/host.access.log  main;
> 
>         location / {
>             grpc_pass grpcs://223.6.6.6:443;
> 			grpc_ssl_protocols TLSv1.3;
> 			grpc_send_timeout 60s;
> 			grpc_read_timeout 60s;
> 			grpc_next_upstream_tries 0;
> 			grpc_next_upstream_timeout 0;
> 			grpc_socket_keepalive on;
>         }
> 
> 	}
> ```
> 
> 反向代理dns over https，但是nginx有bug，
> grpc_socket_keepalive on; 并不生效。

grpc我还没有搞过
