### ISSUE TITLE
How to use http2 long connection to make a request

### ISSUE THREAD

**Issue by f4nff** [AdguardTeam/dnsproxy#158]
Now a request will be interrupted once, so the handshake is very expensive. How to use http2 to keep the connection and continue to initiate the request?
How to enable http2 ping/pongs?

现在请求一次就会中断一次，这样握手开销很大， 如何使用http2保持连接，持续发起请求？
如何开启http2 ping/pongs ?

**Comment by ameshkov** [comment]
dnsproxy 默认用 http2 也保持这个链接。你应该确定服务器也能用http2。

**Comment by f4nff** [comment]
`curl -k -H 'accept: application/dns-message' 'https://223.5.5.5/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB' | hexdump -c`


我确定

**Comment by ameshkov** [comment]
那没问题

**Comment by f4nff** [comment]
@ameshkov 

http2 的ping/pongs 怎么开启，设置？

**Comment by ameshkov** [comment]
请试试master的版本编译

**Comment by f4nff** [comment]
![image](https://user-images.githubusercontent.com/19538878/132018388-af454ecb-e800-416b-a80d-3e1a5c8c57d2.png)
通过抓包，心跳没得问题。
发送间隔30s，多久超时？

**Comment by f4nff** [comment]
`transportH2.ReadIdleTimeout = transportDefaultReadIdleTimeout`


了解。
