### ISSUE TITLE
dns over https 不能分别自定义sni，host，ip:port

### ISSUE THREAD

**Issue by f4nff** [AdguardTeam/dnsproxy#159]
`dnsproxy -p 53 -u https://dns.google/dns-query`

建议搞成

`dnsproxy -p 53 -u https://www.baidu.com/dns-query?ip=8.8.8.8:443&host=dns.google`

这样抓包得到的sni是www.baidu.com，实际host是dns.google

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/dnsproxy/issues/147

我们记得这个问题。有空儿就作了。

**Comment by puteulanus** [comment]
> Duplicates #147
> 
> 我们记得这个问题。有空儿就作了。

请问这个功能目前有实现吗？我在文档里似乎没有找到。因为阿里即将对公共 DNS 按照源 IP 限制频率（ https://www.v2ex.com/t/1058732 ），所以想指定 DoH 上游用 IPv6 的服务器

也就是对 https://dns.alidns.com/dns-query 指定 IP 为 2400:3200::1，或者对 https://[2400:3200::1]/dns-query 指定 SNI 为 dns.alidns.com（阿里的 DoH 证书没有包含 IPv6 的地址作为 host，使用 2400:3200::1 作为 SNI 证书验证会有问题）

目前的替代方案可能有修改运行的机器的 hosts、使用 https://[2400:3200::1]/dns-query 并添加 --insecure 参数、再跑一个 dns 指定 dns.alidns.com 解析为 2400:3200::1 然后把它作为 --bootstrap，老实讲都有点蛋疼
