### ISSUE TITLE
Add "optimistic cache" command-line option

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#160]
dnsproxy什么时候加入刷新缓存
adgh的乐观缓存应该在中国是叫刷新缓存

**Comment by Potterli20** [comment]
@ameshkov 你好，我测试了一下dnsmasq的缓存和dnsproxy的缓存，感觉dnsmasq上的缓存好用dnsproxy我感觉调用不出来。

**Comment by sergeevabc** [comment]
What is optimistic cache and how does it differ from the usual cache?
