### ISSUE TITLE
dnsmasq的缓存和dnsproxy的缓存??

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#165]
@ameshkov @EugeneOne1 
你好，我测试了一下dnsmasq的缓存和dnsproxy的缓存，感觉dnsmasq上的缓存好用dnsproxy我感觉调用不出来。是否能进行一个缓存优化
Hello, I have tested the cache of DNSMasq and dNSProxy. I feel that the cache on DNSMasq is easy to use. I feel that DNSProxy cannot be called. Whether a cache optimization can be performed

**Comment by EugeneOne1** [comment]
@Potterli20, hello.  I'm not quite sure I've got your point.  We already have a few issues on improving the cache (AdguardTeam/AdGuardHome#3598, AdguardTeam/AdGuardHome#2999, #53) so it will evolve and get better.

**Comment by Potterli20** [comment]
> @Potterli20，你好。我不太确定我明白你的意思。我们已经在改进缓存方面[遇到](https://github.com/AdguardTeam/AdGuardHome/issues/3598)了一些问题（[AdguardTeam/AdGuardHome#3598](https://github.com/AdguardTeam/AdGuardHome/issues/3598)、[AdguardTeam/AdGuardHome#2999](https://github.com/AdguardTeam/AdGuardHome/issues/2999)、#53），因此它会不断发展并变得更好。



> @Potterli20, hello. I'm not quite sure I've got your point. We already have a few issues on improving the cache ([AdguardTeam/AdGuardHome#3598](https://github.com/AdguardTeam/AdGuardHome/issues/3598), [AdguardTeam/AdGuardHome#2999](https://github.com/AdguardTeam/AdGuardHome/issues/2999), #53) so it will evolve and get better.

What I want to say is dnSMASQ cache and DNSProxy cache. I find that DNSMASQ cache can be called, while DNSProxy cache gives me a feeling that it is not called

**Comment by EugeneOne1** [comment]
While you're using dnsproxy CLI tool with `--cache` flag I can assure you it's called on almost (see issues from the previous comment) each request.

**Comment by Potterli20** [comment]
> While you're using dnsproxy CLI tool with `--cache` flag I can assure you it's called on almost (see issues from the previous comment) each request.

It didn't work. I switched to 4g cache, but it still didn't feel like I was calling cache. All requests on ADGH come from the DNSMasq program. As I mentioned in a previous post, dnsmasq takes precedence
