### ISSUE TITLE
dns proxy是否可以实时更新上游dns分流文件

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#167]
dns proxy是否可以实时更新上游dns分流文件
是否可以不用重启程序就可以实时更新文件？

**Comment by ameshkov** [comment]
分流文件是什么意思？

**Comment by Potterli20** [comment]
> 分流文件是什么意思？

就是dns分流文件
https://file.trli.club/dns/dns-txt/gfwlist2adguardhome/whitelist_domain_full.txt

**Comment by ameshkov** [comment]
啊，知道了。dnsproxy 不能实时更新，但是你能写脚本自动化。当那个文件更新时重启dnsproxy。

**Comment by Potterli20** [comment]
> 啊，知道了。dnsproxy 不能实时更新，但是你能写脚本自动化。当那个文件更新时重启dnsproxy。

啊，这样，那就麻烦了。因为我有个机器里面用warp，warp的wg里的DNS，设置为127.0.0.1，如果要重启rc.local的，影响就有warp程序，因为dnsproxy设置为开机自启，写在rc.local上的。所以有什么办法呢？

**Comment by ameshkov** [comment]
坦白来说我没有openwrt经验，但我觉得它有办法只重启一个service。

**Comment by ameshkov** [comment]
那我建议用systemd

**Comment by Potterli20** [comment]
> 那我建议用systemd

那如何写？可以写个wiki？

**Comment by Potterli20** [comment]
> 那我建议用systemd

哦，对了，我有多个dns proxy程序需求，不知道是如何写？

**Comment by ameshkov** [comment]
我不能替你写个脚本，只能建议办法。如果你用 rc.d 控制程序，你最好替 rc.d 用 systemd，systemd 网站有很多信息。

**Comment by Potterli20** [comment]
> 我不能替你写个脚本，只能建议办法。如果你用 rc.d 控制程序，你最好替 rc.d 用 systemd，systemd 网站有很多信息。

okkk，我看看看
