### ISSUE TITLE
Why use HTTP/1.1 to crear dns over https server rather then HTTP/2?

### ISSUE THREAD

**Issue by xsy2004** [AdguardTeam/dnsproxy#168]

**Comment by xsy2004** [comment]
no, i mean is dns over https server, not upstream

**Comment by xsy2004** [comment]
Is shoudn't be closed, i doesn't say the upstream not use http/2, it's when dnsproxy be a dns over https server to provide services, dnsproxy can't provide http/2.

**Comment by ameshkov** [comment]
By default it supports both H1 and H2. We can indeed make it configurable, but please open a new issue and explain what exactly you'd like to have in the configuration.

**Comment by xsy2004** [comment]
> By default it supports both H1 and H2. We can indeed make it configurable, but please open a new issue and explain what exactly you'd like to have in the configuration.

ok, thank you for your help, So does the released version support it? or i need to compile the latest version?

**Comment by ameshkov** [comment]
The released version supports both HTTP/1.1 and HTTP/2, but it's up to the client to choose which one would be used.

**Comment by xsy2004** [comment]
> The released version supports both HTTP/1.1 and HTTP/2, but it's up to the client to choose which one would be used.

```
➜  ~ curl -i --http2 https://x.x.x.x:60171/dns-query
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 28 Sep 2021 16:55:18 GMT
Content-Length: 12

Bad Request
```
`dnsproxy --https-port=60171 --tls-crt=/root/routedns/xxxx.pem --tls-key=/root/routedns/xxxx.key -u 127.0.0.1:8053 --edns -p 60170 --udp-buf-size=4096 --max-go-routines=100000`

but i test it, maybe not?

**Comment by xsy2004** [comment]
> The released version supports both HTTP/1.1 and HTTP/2, but it's up to the client to choose which one would be used.

And i try to use master branch code to build dnsproxy, and i test it, it also don't have http/2 support.

**Comment by ameshkov** [comment]
curl advertises that it can use both HTTP/1.1 and HTTP/2 via ALPN, the server prefers HTTP/1.1. If the client advertises only HTTP/2, it will be used.

**Comment by xsy2004** [comment]
> curl advertises that it can use both HTTP/1.1 and HTTP/2 via ALPN, the server prefers HTTP/1.1. If the client advertises only HTTP/2, it will be used.

yes, so i use "curl --http2" to test it, it also to return http/1.1

**Comment by ameshkov** [comment]
Even though you use --http2, curl still advertises that it can use both protocols. If you run curl with `-v` you'll see what it sends in the ALPN extension.

**Comment by xsy2004** [comment]
> Even though you use --http2, curl still advertises that it can use both protocols. If you run curl with `-v` you'll see what it sends in the ALPN extension.

```
➜  ~ curl -v -i --http2 https://xxxxx:60170/dns-query
*   Trying x.x.x.x:60170...
* Connected to x.x.x.x (x.x.x.x) port 60170 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=x.x.x.x
*  start date: Sep 10 12:18:22 2021 GMT
*  expire date: Dec  9 12:18:21 2021 GMT
*  subjectAltName: host "x.x.x.x" matched cert's "x.x.x.x"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /dns-query HTTP/1.1
> Host: x.x.x.x:60170
> User-Agent: curl/7.77.0
> Accept: */*
> 
* TLSv1.2 (IN), TLS alert, close notify (256):
* Empty reply from server
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (52) Empty reply from server
➜  ~ 

```

**Comment by ameshkov** [comment]
```
* ALPN, offering h2
* ALPN, offering http/1.1
```

```
* ALPN, server accepted to use http/1.1
```

**Comment by xsy2004** [comment]
> ```
> * ALPN, offering h2
> * ALPN, offering http/1.1
> ```
> 
> ```
> * ALPN, server accepted to use http/1.1
> ```

It should default to use http/2?
