### ISSUE TITLE
Cache for custom upstream configurations

### ISSUE THREAD

**Issue by Iceman248** [AdguardTeam/dnsproxy#169]
### Issue Details

* **Version of AdGuard Home server:**
 v0.107.0-b.11, issue started on v0.106.3, still issue after upgrading to beta
* **How did you install AdGuard Home:**
  Docker using Unraid Community Apps
* **How did you setup DNS configuration:**
  DNS assigned via DHCP from router, AGH goes straight to NextDNS as upstream

### Expected Behavior
many queries showing fractional ms times

### Actual Behavior
Typical ping times for everything, nothing being cached, NextDNS showing many times over more queries as a result

</details>

### Additional Information
Starting happened in the last 24 hours

**Comment by Iceman248** [comment]
Thanks. What is the reason that custom upstream clients can't use the global cache? Is that a permanent situation? What is the limitation with that?

**Comment by ameshkov** [comment]
Usually, custom upstreams do additional filtering. For instance, if a client is a Kids device, people may choose to use an upstream that blocks adult websites. Using a global cache would be inconsistent in this case.

**Comment by Iceman248** [comment]
Okay, I see. What about for one of the options in the client settings to choose whether or not that client uses the global cache?

**Comment by EugeneOne1** [comment]
@Iceman248,

**Comment by emlimap** [comment]
At the moment I run blocky in the middle between AGH & DOH/DoT upstreams for the sole purpose of caching, and would like to get rid of it when dnsproxy/AGH get caching support for custom up streams.

Also, blocky seems to support custom upstream per client. Not sure how they implement caching for this as I use it with just default upstream. https://0xerr0r.github.io/blocky/configuration/#upstream-configuration

Source code for blocky https://github.com/0xERR0R/blocky

**Comment by Iceman248** [comment]
I'm confused after reading the other linked threads. Was this actually resolved or not?

**Comment by Mizzick** [comment]
@Iceman248, I have fixed this on the side of the dnsproxy. If you want to test this client's cache urgently with AdGuard Home, please have a look on the latest edge build version `v0.108.0-a.762+388583ce`. Nonetheless it yet doesn't have an UI to set the settings, but we have added new properties in YAML config `clients.persistent.upstreams_cache_enabled` and `clients.persistent.upstreams_cache_size` which describe cache configuration for each client custom upstream configuration.
