### ISSUE TITLE
Are MITM attacks when using DNS-over-TLS, DNS-over-HTTPS or DNS-over-QUIC possible?

### ISSUE THREAD

**Issue by phantomcraft** [AdguardTeam/dnsproxy#173]
I can use DNS-over-TLS, DNS-over-HTTPS and DNS-over-QUIC in this way in **dnsproxy**:

```
-u tls://dns.adguard.com
-u https://dns.adguard.com/dns-query
-u quic://dns.adguard.com
```

But there is no certificate pinning or digests of keys in these modes. Does it makes vulnerable to MITM attacks?

https://en.wikipedia.org/wiki/Man-in-the-middle_attack

**Comment by ameshkov** [comment]
Generally, TLS (which is used by all three) is supposed to protect from MITM attacks and no pinning is required for that.

Pinning is a double-edged sword that on one hand solidifies protection, but on the other hand, it requires constant care, certificates change on servers and you can't control it.

dnsproxy does not support pinning at the moment. If you'd like it to be added, please file a feature request. If it's upvoted, we may add it in the future.
