### ISSUE TITLE
QUIC address resolving?

### ISSUE THREAD

**Issue by Owyn** [AdguardTeam/dnsproxy#175]
I used QUIC example on my win10 machine
`./dnsproxy -u quic://dns.adguard.com`
and it simply didn't work cuz it couldn't resolve it:

````
2021/10/11 13:37:45 7708#24 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): failed to lookup for dns.adguard.com in 510.1µs using : lookup dns.adguard.com: no such host
2021/10/11 13:37:45 7708#24 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): failed to lookup for dns.adguard.com in 0s using : lookup dns.adguard.com: no such host
2021/10/11 13:37:45 7708#24 [debug] github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(): upstream quic://dns.adguard.com:8853 failed to exchange ;yandex.ru.   IN       AAAA in 1.1105ms. Cause: failed to lookup dns.adguard.com, cause: lookup dns.adguard.com: no such host
2021/10/11 13:37:45 7708#24 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).replyFromUpstream(): RTT: 6.3067ms
2021/10/11 13:37:45 7708#24 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: SERVFAIL, id: 3
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;yandex.ru.     IN       AAAA

2021/10/11 13:37:45 7708#24 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): error handling DNS (udp) request: talking to dnsUpstream failed, cause: failed to lookup dns.adguard.com, cause: lookup dns.adguard.com: no such host
2021/10/11 13:37:45 7708#29 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 127.0.0.1:61643
2021/10/11 13:37:45 7708#29 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 4
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
````

`-u quic://94.140.14.14 -u quic://94.140.15.15` seemed to work tho - is there any downside to using this variant so no time'd be wasted on resolving dns domain?

**Comment by Owyn** [comment]
Ah I see.

but, is there any reason I shouldn't use `-u quic://94.140.14.14 -u quic://94.140.15.15` instead of `quic://dns.adguard.com -b` ?

**Comment by Owyn** [comment]
Well, for not quic protocols adguard tells ppl to use its IPs in their instructions, so in case they suddenly change their IPs - 90% of their userbase would get broken internet

**Comment by schorschfunke** [comment]
Thats right

**Comment by glassman81** [comment]
> Actually, we'd prefer if you used the domain name and not IP.
> 
> Regarding the issue in question, if you don't specify the bootstrap server. By default, AdGuard uses the system DNS so I am not sure why it cannot resolve `dns.adguard.com`. Is your system DNS intact?

I know this is older, but why? It seems like it would eliminate the need for a bootstrap server, and most dns is set through IP anyway- because you need to know the IP of a resolver before you start resolving. Why not just cut out the middleman?
