### ISSUE TITLE
Get rid of `github.com/jessevdk/go-flags` dependency

### ISSUE THREAD

**Issue by EugeneOne1** [AdguardTeam/dnsproxy#182]
Currently, we're using `github.com/jessevdk/go-flags` module to handle configurable options in CLI tool but it provides some notable restrictions and design issues.  For example, in #170 which adds the `.yaml` configuration file support we've came across the inability to properly combine the parsed options' values with values from the file.

Moreover, the functionality provided by `go-flags` doesn't actually justify abandoning of `flag` from standard library.  Since we strive to keep unnecessary dependencies to a minimum, the one should be removed.

**Comment by Mizzick** [comment]
Fixed in `v0.73.2`.
