### ISSUE TITLE
Cannot use udp:// scheme

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#184]
./dnsproxy -u udp://114.114.114.114 -p 54
2021/11/04 12:46:56 [fatal] error while parsing upstreams configuration: cannot prepare the upstream udp://114.114.114.114 ([]): unsupported URL scheme: udp

**Comment by Potterli20** [comment]
![图片](https://user-images.githubusercontent.com/28734349/140259752-c72bed76-2715-484b-9967-84628a50bd8d.png)
本来是这样写的

**Comment by ameshkov** [comment]
对，你不能只用 udp 因为这样有些域名dnsproxy不能解析。这些域名的 DNS message 太大的。
