### ISSUE TITLE
Add option for wildcard resolving

### ISSUE THREAD

**Issue by DUOLabs333** [AdguardTeam/dnsproxy#189]
Can you add an option so that all `*.test` resolves to `x.x.x.x`?

**Comment by ameshkov** [comment]
dnsproxy does not do filtering, it's just a forwarder.

If you need more than that, consider using AdGuard Home instead, it is built on top of dnsproxy and provides filtering capabilities.

**Comment by DUOLabs333** [comment]
I actually do run AdGuard Home on my server, and used to run it on my phone, but didn't want to handle both.
