### ISSUE TITLE
Can not run a server on 0.0.0.0, it turns to [::] instead automatically

### ISSUE THREAD

**Issue by CDLLY** [AdguardTeam/dnsproxy#190]
![image](https://user-images.githubusercontent.com/20614068/142793658-bf120f1b-2da8-4d78-91c3-ffc65c016bb9.png)

It is working on 127.0.0.1, but on 0.0.0.0, it use ipv6 instead of ipv4, and unfortunately, I can not access my server with ipv6...

Of course, I can use webserver like nginx to proxy it, but this seems to be a bug.

**Comment by ameshkov** [comment]
> it use ipv6 instead of ipv4

This is not IPv6, this is actually IPv4+IPv6, all interfaces.

This is how server sockets work in Golang. If you specify `0.0.0.0` it is automatically converted to `::`.
