### ISSUE TITLE
Add web GUI interface to dynamic change config and then apply to restart it.

### ISSUE THREAD

**Issue by cnmade** [AdguardTeam/dnsproxy#199]
for example: if we want to change the configure and make it apply to dnsproxy, we need a better User interface.
I guess we can get a Web GUI interface to let user to dynamic configure or whatever.

Or Will you please expose RPC or Restful API for us, that we can build third party WebGui, or native GUI interface.

**Comment by ameshkov** [comment]
dnsproxy is supposed to be a command-line tool with no UI.

On the other hand, there's AdGuard Home that is built on top of dnsproxy and provides web UI.
