### ISSUE TITLE
Multiple listen addresses

### ISSUE THREAD

**Issue by alvussar** [AdguardTeam/dnsproxy#20]
Add multiple listing address
eg. dnsproxy -l 127.0.0.1 -l 127.0.0.2

**Comment by dsheets** [comment]
Unless I misunderstand, I think this feature was added by @szolin in https://github.com/AdguardTeam/dnsproxy/commit/7b79d1c7e5292aa0a3a8440e9ac794e204ae29f3 on 2020-07-20 and released in https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.30.0 .

**Comment by ameshkov** [comment]
Yep, that's right
