### ISSUE TITLE
dnsproxy not design for stability

### ISSUE THREAD

**Issue by cnmade** [AdguardTeam/dnsproxy#201]
DNS is very important, if no right DNS resolve, you can not got much things working right. For windows 11, you may not upgrade to latest windows. you can not access Microsoft store.

So the current DoH, DoQ, DoT, if them was blocked for some reason.
you can not easy to get with it.

DNSProxy should be think get better fail back support.

Auto migrate DNS resolve failed problem for user.

1. If DoQ failed, try DoT;
2. If DoT failed, try DoH;
3. If DoH failed, try DNS over TCP;
4. If DNS over TCP failed, try DNS over udp:53
5. if both failed, try next upstream?
6. if all upstream failed. how to auto migrate it ?

DNS is complex. and dnsproxy is complex .
How do you think?

**Comment by ameshkov** [comment]
We're considering this change (e.g. try every upstream one by one until at least one succeeds) and there's already an open report about that in AdGuard Home repo. Most likely, this will be a separate option.

Meanwhile, dnsproxy already provides two options that could help:

* `--all-servers` -- it'll send a query to all upstreams and the first successful response will be returned to the user
* `--fallback` -- allows to specify a fallback upstream.
