### ISSUE TITLE
Something's wrong here?

### ISSUE THREAD

**Issue by Takaki-Sakura** [AdguardTeam/dnsproxy#203]
I just set up a local dnsproxy with command 
```
dnsproxy -u https://dns.adguard.com:443/dns-query -v -o log.txt
```
i am using AMD64 build
but i am getting could not connect here is the full log:
https://sourceb.in/xzretn3nIl

**Comment by ameshkov** [comment]
Could it be that `dns.adguard.com` times out from your place?

What happens if you configure a shorter timeout for queries?

**Comment by Takaki-Sakura** [comment]
No, `dns.adguard.com` works fine from here

So, i was testing some things and i found that if i add doh/dot requests is not resolved but once i add fallback it get resolves such as from `dns.adguard.com`, i used `dnsleaktest.com` whether it is resolving from fallback i found it is resolved from `dns.adguard.com` itself. But if i removed fallback after closing the program it is working as intended. i tried the same thing with cloud flare and google found same results adding and removing fallback

Conclusion: if a doh/dot is added, adding fallback (normal udp) solves it. then the fallback can be removed

**Comment by ameshkov** [comment]
What bothers me in your log is that I don't see any errors or responses. If you could run dnsproxy with a shorter timeout or just wait for some time, maybe the log will be more useful.

**Comment by Takaki-Sakura** [comment]
can u tell me the parameter for it?

**Comment by ameshkov** [comment]
Huh, good question, it seems we haven't exposed it to the command-line interface 🤦 

Anyways, the default value for it is 10 seconds. Please let it work for at least 10 seconds before grabbing the log.

**Comment by Takaki-Sakura** [comment]
Here: https://pastebin.com/raw/DV0s82UZ

**Comment by ameshkov** [comment]
```
2022/02/11 19:20:53 9736#18 [debug] github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(): upstream tls://dns.adguard.com:853 failed to exchange ;www.google.com.	IN	 A in 10.0033919s. Cause: getting connection to tls://dns.adguard.com:853: lookup dns.adguard.com: i/o timeout
```

It actually looks like you have an infinite loop here. dnsproxy tries to resolve `dns.adguard.com`, but your system is configured to use `dnsproxy` as the default resolver, so it asks itself. Then again and again.

You need to configure bootstrap DNS explicitly so that dnsproxy was using it to resolve `dns.adguard.com`.
