### ISSUE TITLE
是否能写个docker 的dnsproxy？

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#205]
如题

**Comment by Potterli20** [comment]
能用systemctl 就行了
因为我不会去写，希望你们帮我去写一个，也是其他用户想用的

**Comment by Potterli20** [comment]
https://github.com/AdguardTeam/AdGuardHome/discussions/4305

**Comment by ameshkov** [comment]
Closing this as a duplicate of #208, I've also responded there.
