### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by BigmenPixel0** [AdguardTeam/dnsproxy#208]
It would be nice if there was an official docker image.

**Comment by Potterli20** [comment]
#205

**Comment by ameshkov** [comment]
Let's keep this one open since it's in English.

Generally, it's of course possible to have an official docker image, it'd just take a day of work.
If anyone would like to contribute a Dockerfile, please check out how we build it in AdGuard Home: https://github.com/AdguardTeam/AdGuardHome/blob/master/scripts/make/build-docker.sh

**Comment by Potterli20** [comment]
> Let's keep this one open since it's in English.
> 
> Generally, it's of course possible to have an official docker image, it'd just take a day of work.
> If anyone would like to contribute a Dockerfile, please check out how we build it in AdGuard Home: https://github.com/AdguardTeam/AdGuardHome/blob/master/scripts/make/build-docker.sh

But the systemctl problem is unsolved

**Comment by vmstan** [comment]
Not official but I've been maintaining my own Docker container for some time now.
https://hub.docker.com/r/vmstan/dnsproxy

**Comment by PeterDaveHello** [comment]
Is it possible that a simple Dockerfile can be acceptable at first? I can send a pull request for it if that's good enough.

**Comment by pataquets** [comment]
Thanks chiming in, @PeterDaveHello . There is an ongoing PR at #228 if you feel like to help.

**Comment by ameshkov** [comment]
https://hub.docker.com/r/adguard/dnsproxy

**Comment by ameshkov** [comment]
You basically use it the same way as the original binary:
```
docker run --rm -p 53:53/udp -p 53:53/tcp adguard/dnsproxy -c config.yml
```
