### ISSUE TITLE
Would you like to hide DoH http user-agent header?

### ISSUE THREAD

**Issue by PeterDaveHello** [AdguardTeam/dnsproxy#211]
Currently, the user-agent header that will be sent when using DoH is `Go-http-client/2.0`, though we know that there're many profiling mechanisms to find out the tools and details about the users, but maybe it'll be great if we can give one less information, like user-agent string.

That's what are Firefox and iOS doing, both known as privacy-protected products, not sure if this is this something dnsproxy would like to do? I've prepared a patch that can be submitted as a pull request if it'll be accepted here ;) What do you think?

**Comment by ameshkov** [comment]
Tbh, I think the proper approach would be to not send user-agent header at all, just like Mozilla does: https://bugzilla.mozilla.org/show_bug.cgi?id=1543201

**Comment by PeterDaveHello** [comment]
PR sent in https://github.com/AdguardTeam/dnsproxy/pull/212, thanks @ameshkov!
