### ISSUE TITLE
Does not support go1.18

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#218]
Does not support go1.18

**Comment by Potterli20** [comment]
Quic-go Does not support go1.18

**Comment by Potterli20** [comment]
![Screenshot_2022-03-21-12-49-38-000_com.github.android.jpg](https://user-images.githubusercontent.com/28734349/159206906-56edf4d1-7b9e-42b3-b18a-83f181a8d9b5.jpg)

miekg/dns和lucas的quic-go冲突了

**Comment by Potterli20** [comment]
手动更新1.18已经正常
请更新全部依赖，谢谢

**Comment by ainar-g** [comment]
@Potterli20, we have updated the dependency on the `master` branch.  Can you please check if it works for you now?

**Comment by Potterli20** [comment]
> @Potterli20, we have updated the dependency on the `master` branch.  Can you please check if it works for you now?

![Screenshot_2022-03-21-20-06-19-898_com.github.android.jpg](https://user-images.githubusercontent.com/28734349/159257782-7d375c17-1c38-443e-912a-e2cdc06871e7.jpg)![Screenshot_2022-03-21-20-05-27-470_com.github.android.jpg](https://user-images.githubusercontent.com/28734349/159257791-5a424066-00d8-4dd9-a850-3ef0cd8e8b36.jpg)
I wrote this document

**Comment by Potterli20** [comment]
> @Potterli20, we have updated the dependency on the `master` branch.  Can you please check if it works for you now?

I also fork your project and it is normal for me to make changes myself

https://github.com/potterli20/dnsproxy

**Comment by ainar-g** [comment]
I see.  We'll consider adding dependabot to the main repo in the future.  AdGuard Home should be updated sometime within this week.  We'll close this issue for now.

**Comment by Potterli20** [comment]
> I see.  We'll consider adding dependabot to the main repo in the future.  AdGuard Home should be updated sometime within this week.  We'll close this issue for now.

okkk

**Comment by Potterli20** [comment]
> I see.  We'll consider adding dependabot to the main repo in the future.  AdGuard Home should be updated sometime within this week.  We'll close this issue for now.

Adgh will also be updated
