### ISSUE TITLE
QUIC address breaks DNS resolution

### ISSUE THREAD

**Issue by joshcangit** [AdguardTeam/dnsproxy#234]
I've made a systemd service to use `dnsproxy`.
Couldn't see any errors but if I use `quic://` address for DNS-over-QUIC, it will fail.
Even with fallback DNS options, it still fails.
There seems to be http3 but so far I only know 1 site that provides DNS over http3.

**Comment by ameshkov** [comment]
Hi!

DoQ and DoH are different things, you cannot use a `quic://` URL for a server that does not support it.

**Comment by joshcangit** [comment]
> DoQ and DoH are different things, you cannot use a `quic://` URL for a server that does not support it.

It won't work if quic port is not **853**.

Yes, I even did a `dnslookup` test. The URLs exist but on different ports.
### dnslookup
`dnslookup github.com quic://dns-unfiltered.adguard.com:784`
```
dnslookup v. 1.6.0-7201
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 5745
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;github.com.	IN	 A

;; ANSWER SECTION:
github.com.	60	IN	A	20.205.243.166
```
`dnslookup github.com quic://ultralow.dns.nextdns.io:8853`
```
dnslookup v. 1.6.0-7201
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 20678
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;github.com.	IN	 A

;; ANSWER SECTION:
github.com.	30	IN	A	20.205.243.166
```

**Comment by ameshkov** [comment]
`ultralow.dns.nextdns.io` - it seems to be using the old draft of the DoQ spec, does not work with the new version of `dnslookup` and `dnsproxy`
