### ISSUE TITLE
Quic not working after update to 0.43.0

### ISSUE THREAD

**Issue by Handsome1080P** [AdguardTeam/dnsproxy#238]
Server Side: ```dnsproxy -l 0.0.0.0 --quic-port=8853 -p 0 --tls-crt=fullchain.pem --tls-key=privkey.pem -u tls://1.1.1.1 -b 1.1.1.1:53```
Client Side: ```dnsproxy -l 127.0.0.1 -p 55 -u quic://www.server.com:8853```
Test got error:

> ;; Warning: ID mismatch: expected ID 45488, got 0

**Comment by Handsome1080P** [comment]
dnsproxy log:

> ;; QUESTION SECTION:
;google.com.    IN       A

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096
; COOKIE: 361dd5693329f35a

2022/06/04 12:11:56 11206#37 [debug] time.Duration.Milliseconds(): upstream quic://www.405218.xyz:8853 successfully finished exchange of ;google.com.   IN       A. Elapsed 53.903014ms.
2022/06/04 12:11:56 11206#37 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).replyFromUpstream(): RTT: 54.043176ms
2022/06/04 12:11:56 11206#37 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 0
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

**Comment by Xjoion** [comment]
I have the same problem as you

**Comment by ameshkov** [comment]
@Xjoion @Handsome1080P hi all, thank you for reporting it, I'll look into it today

**Comment by Handsome1080P** [comment]
> @Xjoion @Handsome1080P hi all, thank you for reporting it, I'll look into it today

I update from 0.42 to 0.43 just now.the lastest version has released about 11days,no one use quic?
