### ISSUE TITLE
是否能加个dnssec选项

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#243]
如:--dnssec 
Adh上好像也有dnssec选项了

**Comment by ameshkov** [comment]
DNSSEC 应该实行在 “recursor” 类的 DNS 服务器 （比如 AdGuard DNS、Google DNS、这样服务器）。dnsproxy 不是 “recursor”，是 “forwarder“，它凭借上游的服务器检查 DNSSEC。
