### ISSUE TITLE
Question: How to make up Responses

### ISSUE THREAD

**Issue by mitnk** [AdguardTeam/dnsproxy#244]
Hey, thanks for this project, super useful!

In a fork, I want to blacklist some domains. Want to make the A records always be "127.0.0.1".

In `proxy/proxy.go:replyFromUpstream()`, I tried something like this:

```go
func (p *Proxy) replyFromUpstream(d *DNSContext) (ok bool, err error) {
	req := d.Req
	host := req.Question[0].Name
	if strings.Contains(host, "somedomain.com") {
		reply = new(dns.Msg)
		reply.MsgHdr = dns.MsgHdr{Response: true}
		reply.Response = true
		reply.SetRcode(req, dns.RcodeSuccess)
		reply.SetQuestion(host, dns.TypeA)
		rr, _ := dns.NewRR(fmt.Sprintf("%s 3600 IN A 127.0.0.1", host))
		reply.Answer = append(reply.Answer, rr)
		d.Res = reply
		d.Upstream = upstreams[0]
		return true, nil
	}

	... the original logics ...
	reply, u, err = p.exchange(req, upstreams)
	...
	return ok, err
}
```

But the client will stuck and timed out. Any ideas? Thanks you!

**Comment by ameshkov** [comment]
Hi!

The client times out because the ID of your response does not match the request's ID.

You should do `reply.SetReply(d.Req)`.

**Comment by mitnk** [comment]
It works. Thanks you @ameshkov
