### ISSUE TITLE
How to forward real client IP to upstream server

### ISSUE THREAD

**Issue by m0zgen** [AdguardTeam/dnsproxy#245]
Hello,

How can I forward real client ip to DNS upstream servers? As example, if I'm using `dnsproxy` on same DNS server host as DoH server / DNS requests forwarder, in the local DNS server logs all requests logged as `127.0.0.1`. If possible I need forward from `dnsproxy` - real client IP addresses to local DNS server, it is possible?

Thank you in advance.

**Comment by ameshkov** [comment]
We have a feature request about that:
https://github.com/AdguardTeam/dnsproxy/issues/166

Haven't got time to implement this, but I suppose it will be done in the coming months.
