### ISSUE TITLE
Make blocked TTL's shorter like in AdGuard Home with "blocked_response_ttl" setting

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/dnsproxy#247]
Would be really nice if you could configure blocked domains separately to get a shorter TTL, so whitelisting is faster to clients.
Could the code maybe be copied straight from AdGuard Home, so it's a "low hanging fruit" to fix?!

**Comment by ameshkov** [comment]
Well, the thing is that dnsproxy does not block anything so it just does not need that settings. This probably should be done on NextDNS side. 

In AdGuard DNS we do provide such a setting:
![image](https://user-images.githubusercontent.com/5947035/181918893-86feae79-038e-4752-a4f6-f13d039cdd86.png)

**Comment by iJorgen** [comment]
I just thought it would be nice if it could be done the same way as you rewrite min-TTL/max-TTL values to clients.
If the answer is "0.0.0.0" or NXDOMAIN from upstream, it would return the specified TTL-value to clients. It should not block anything, just adjust the TTL for blocked queries. :-)

**Comment by ameshkov** [comment]
Well, it just seems to me that dnsproxy is not a right place to do that:)

dnsproxy is supposed to be a rather simple DNS forwarder, all the complicated stuff should be done by the upstream.

**Comment by iJorgen** [comment]
Got it... I'm very pleased with DNSproxy performance/caching and running great on my router using DoQ.
Also following your progress on AdGuard Home and AdGuard DNS. Keep up the good work! :-))
