### ISSUE TITLE
A bug when using several different upstream-protocols?!

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/dnsproxy#248]
I did a setup with three different upstream sources/protocols. One with Quic, one with DoT and one with DoH. The flag "all-servers" was set to "true" and all pointing to NextDNS.
What I noticed was that all DoH queries was immediately followed by a TLS query with exactly the same result (duplicates) in the logs. A bug?!
Also it seemed to ignore using Quic. Could this be since DoT is using/occupying the same port (853)?

**Comment by ameshkov** [comment]
That's how "all-servers" is supposed to work. In this mode it sends queries to ALL upstreams at the same time and returns the first response it gets.
