### ISSUE TITLE
Cache-size in Kb related to number of DNS-entries

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/dnsproxy#251]
I saw in history that the default cache-size was changed from "number of items" to bytes. 1000 items was changed to 64kb.

Could you draw the conclusion that each DNS-entry is in average 64 byte? So if I set a cache-size of 256kb it would store approximately 4000 DNS-entries and so on?

**Comment by ameshkov** [comment]
An average DNS response size is in the range of 100 to 200 bytes.

64kb is just an arbitrary number, the cache size depends on your needs. If the load is not heavy, I'd say 100-200kb is enough.
