### ISSUE TITLE
DNS Benchmarking tools available for all protocols?

### ISSUE THREAD

**Issue by Unknown78** [AdguardTeam/dnsproxy#254]
I couldn't find any benchmark tools that support all of plain DNS, DoH, DoT, DNSCrypt, and DoQ, .

Where could I find it? Does the AdguardTeam already publicize the tools?

**Comment by ameshkov** [comment]
Nope, we don't provide any.

**Comment by Unknown78** [comment]
Yes I mean, is there any such tools out there? How do people usually benchmark with all the protocols then?

**Comment by ameshkov** [comment]
If we're talking client-side benchmarking, you can use dnslookup and write some simple scripts to see how each protocol performs.

And on the server side we have a bunch of metrics we're looking at to measure how it performs.

**Comment by neneeen** [comment]
@Unknown78 Rejoice https://github.com/ameshkov/godnsbench
