### ISSUE TITLE
不支持go 1.19

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#255]
![Screenshot_2022-08-08-08-41-02-092_com.termux.jpg](https://user-images.githubusercontent.com/28734349/183318135-1dc12d15-f3d8-464a-a079-85a22966a445.jpg)

**Comment by ainar-g** [comment]
@Potterli20, this module is used for AdGuard Home, which is still on Go 1.18.  Please do not update anything without consulting us first.  Thank you.
