### ISSUE TITLE
DoH server template/URL

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/dnsproxy#259]
I have setup DNSproxy on my router with DoH and wants to connect to it from my Windows 11 PC with the native DoH-settings, but can't figure out how I should format the "template" I need to specify in Windows 11. If I enter 8.8.8.8, Windows fills out the field with "https://dns.google/dns-query".

Is it like "https://192.168.1.1/dns-query"? Tried lots if different variants, but Windows 11 don't accept any of them.

**Comment by ameshkov** [comment]
I vaguely remember that you need to add the template to Windows registry or using `netsh`:
https://www.howto-connect.com/turn-on-dns-over-https-enableautodoh-windows-10/

**Comment by ameshkov** [comment]
It depends on what DNS server you're trying to use :)
