### ISSUE TITLE
version

### ISSUE THREAD

**Issue by alvussar** [AdguardTeam/dnsproxy#26]
add please param key "--version" to display the dnsproxy version

**Comment by ameshkov** [comment]
Done

**Comment by alvussar** [comment]
Don't work
![dnsproxy](https://user-images.githubusercontent.com/26434853/53225504-ea87e880-3680-11e9-8d34-aeeaf39d8d2d.png)

**Comment by alvussar** [comment]
Don't work
![image](https://user-images.githubusercontent.com/26434853/53286175-023f9980-3773-11e9-812d-e8f6455fb50a.png)

**Comment by ameshkov** [comment]
@admitrevskiy well, something is wrong with the Travis build script?

**Comment by admitrevskiy** [comment]
Done.
