### ISSUE TITLE
dnsproxy produces too many logs for connection issues

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#263]
https://github.com/AdguardTeam/dnsproxy/commit/f89e1bb91a3726db7c21617df60552acf2eeb0e9?notification_referrer_id=NT_kwDOAbZzjbM0Mjk5NDc0MzQ4OjI4NzM0MzQ5&notifications_query=is%3Aunread#commitcomment-82615652

In fact, I don't understand why DOQ has such a problem. It is correct to write on the ADG client, but it will appear on the DNSProxy server, while DOT is normal

**Comment by ainar-g** [comment]
As discussed previously, please add the information about what upstream you're using and what client you're using.  As well as a reproducer using `dnslookup`, if you can.

 >  https://security.googleblog.com/2022/07/dns-over-http3-in-android.html

DNS-over-HTTP/3 and DNS-over-QUIC are *different protocols.*  `dnsproxy` doesn't support DNS-over-HTTP/3 yet.

**Comment by ainar-g** [comment]
Yes.  Preferably from `master` branch.

**Comment by ainar-g** [comment]
Everything seems to be normal.  If your upstream and all other clients are up-to-date as well, it doesn't seem like there is an issue.  DoQ is a relatively new standard, and such compatibility issues will probably not disappear for another year or so, so I would suggest either keeping all of your clients and upstreams up-to-date and following the standard or using DoT and/or DoH instead.

**Comment by ainar-g** [comment]
There is a PR waiting for @ameshkov.  See ameshkov/dnslookup#32.  You can try building from there.

**Comment by ainar-g** [comment]
@Potterli20, I do not understand the question, sorry.  Please write your questions in any language you're comfortable with.

**Comment by ainar-g** [comment]
How is cache relevant to errors in logs?

Please, keep the discussion relevant to the issue.  This is an issue tracker and not a discussion forum.
