### ISSUE TITLE
Optimal tweaks for best DNS-performance?

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/dnsproxy#264]
Any tips or tweaks to make DNSproxy run more efficient on an ASUS router with ~40 devices?
I have only changed "rmem_max" to get rid of the warning saying it can't allocate 2048 kB at startup.

Would changing any of these keys make any positive difference? These are the default values...

- /proc/sys/net/core/rmem_default = 524288
- /proc/sys/net/core/rmem_max = 524288 (changed to 2500000)
- /proc/sys/net/core/wmem_default = 524288
- /proc/sys/net/core/wmem_max = 524288
- /proc/sys/net/core/optmem_max = 20480
- /proc/sys/net/core/netdev_max_backlog = 1000
- /proc/sys/net/core/somaxconn = 128
- /proc/sys/net/ipv4/tcp_max_syn_backlog = 128
- /proc/sys/net/ipv4/udp_rmem_min = 4096
- /proc/sys/net/ipv4/udp_wmem_min = 4096
- /proc/sys/net/ipv4/tcp_rmem = "4096 87380 6291456"
- /proc/sys/net/ipv4/tcp_wmem = "4096 16384 4194304"
- /proc/sys/net/ipv4/udp_mem = "21747 28998 43494"
- /proc/sys/net/ipv4/tcp_mem = "21747 28998 43494"
- /proc/sys/net/ipv4/tcp_max_tw_buckets = 4096
- /proc/sys/net/ipv4/tcp_keepalive_time = 1800
- /proc/sys/net/ipv4/tcp_keepalive_intvl = 30
- /proc/sys/net/ipv4/tcp_keepalive_probes = 5
- /proc/sys/net/ipv4/tcp_fastopen = 1
- /proc/sys/net/ipv4/tcp_slow_start_after_idle = 0

Any other keys not mentioned above to tweak?!

**Comment by ameshkov** [comment]
> I have only changed "rmem_max" to get rid of the warning saying it can't allocate 2048 kB at startup.

If you don't use DNS-over-QUIC you can safely ignore this.

Generally, I wouldn't recommend changing the default settings, it rarely helps, but it can often lead to absolutely mysterious issues :)
