### ISSUE TITLE
You can update GO's dependency cache. I see that the official update is not happening, but other secondary development cache works well too.

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#265]
For example, go cache of zgo.at/zcache.

Just because it seems to me that the cache is not as good as the original GO cache. Emmm watch yours.

Maybe this needs to be added as well.

**Comment by ainar-g** [comment]
>  zgo.at/zcache

In the README:

 >  How can I limit the size of the cache? Is there an option for this?
 >
 >  Not really; zcache is intended as a thread-safe map with time-based eviction.  This keeps it nice and simple.  \[…\]

Meanwhile, limiting the byte size of the cache is important to both `dnsproxy` and AdGuard Home.
