### ISSUE TITLE
Can we limit only one user could use Dns over Tls?

### ISSUE THREAD

**Issue by Mandofskii** [AdguardTeam/dnsproxy#267]
I mean if we have two DoTs :
1. abcdefghijk.ourdomain.com
2. abcjsiwmqjeb.ourdomain.com
And 3 users:
1. user 1
2. user 2
3. user 3

I want only two users of below users can connect to dns
for example:
if user 1 is using the DoT 1 user 2 cant use that
if user 1 use DoT1 and user 2 use DoT2 the third user can not use each of them

is it possible ?

**Comment by ameshkov** [comment]
Not possible using mere dnsproxy.

You'll need to use dnsproxy as a library and code these limitations.
