### ISSUE TITLE
Want to know the Android DOH3 problem

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#270]
Android DOH3 port is 853? Or that one?
If it is QUIC, DOH3 is 853, then QUIC of DNSproxy is not the standard of DOH3.

**Comment by ameshkov** [comment]
DOQ and DOH3 are different protocols, you're confusing them.

**Comment by ameshkov** [comment]
You cannot, we don't support DOH3 yet.

**Comment by ameshkov** [comment]
dnsproxy 下个版本和 AdGuard DNS 下个版本会支持 DOH3，请等一下。
