### ISSUE TITLE
Does not automatically switch back to origin

### ISSUE THREAD

**Issue by ThisIsQasim** [AdguardTeam/dnsproxy#271]
Thanks for the great piece of software. 

One bug I noticed is that after switching to the fallback servers `dnsproxy` does not switch back to the origin servers unless restarted. Any suggestions?

**Comment by ThisIsQasim** [comment]
Any insight into the fallback mechanism would be great in general though #179

**Comment by ameshkov** [comment]
Hi, the current fallback mechanism is rather simple, it will only switch to a fallback when an upstream failed to response.

It does not "switch" to a fallback state and attempts to use the upstream on every request.

**Comment by ThisIsQasim** [comment]
Thanks for the response. In my experience after switching on a failed upstream response, it sticks to the fallback servers till it's restarted

**Comment by ameshkov** [comment]
What protocol do you use? Could be a protocol specific issue (for instance, the upstream fails because it tries to use a dead connection or something like that).

**Comment by ThisIsQasim** [comment]
Yeah that could be why. I am using http3

**Comment by ameshkov** [comment]
Yeah, this is definitely it then. There'll be one more big change (probably today) that improves DoH3 upstream support and adds DoH3 server-side.

**Comment by ameshkov** [comment]
Has just been merged btw: https://github.com/AdguardTeam/dnsproxy/commit/a03a56c89026753989a4b06787ef1a08dfbabb9c

Try using the updated version please.

**Comment by ThisIsQasim** [comment]
Already updating. Will let it run for a few hours and report back if any issues persist. Thanks again!

**Comment by ThisIsQasim** [comment]
Failovers look to be working as expected. Thanks again!

**Comment by ameshkov** [comment]
Awesome

**Comment by MadSpindel** [comment]
> it will only switch to a fallback when an upstream failed to response.

And how do you define _ upstream failed to response_? Is it something like when the response takes longer than 1 second or similar?
