### ISSUE TITLE
Optimistic/Pessimistic cache

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/dnsproxy#272]
I'm a bit confused... ;-) I read that "optimistic caching" in general means that it first tries online before using a cached result and "pessimistic caching" is using a cached result before going online. Is that correct for DNSproxy too?

If I have optimistic caching turned on and I can see the same queries in the DNS-log upstream several times within seconds if I start the same app on different devices. So it queries the upstream servers each time and don't primarily use the cache?! Would it be better to not use optimistic caching to make it use the cached results first?! I wanna do "pessimistic caching" to use the cache first.

Found a site describing it. Not about DNS, but the same principles...
[https://itnext.io/caching-in-a-pwa-when-to-use-optimistic-vs-pessimistic-d627a5943990](url)

**Comment by agneevX** [comment]
Optimistic caching in dnsproxy returns a result from the cache to the client immediately (with a TTL of 10 if expired), then attempts to refresh the record. If it cannot refresh it, it continues to serve the stale record.

**Comment by saint-lascivious** [comment]
The optimism in context comes from serving possibly expired records on an "eh, whatever, YOLO" basis on the probability that the cached record will probably still be correct while refreshing that record in the background if possible so even if it's wrong at that moment the next query won't be.

Various other implementations may also add finer controls determining what the flow should look like if that record can't be refreshed. Such as whether to drop it entirely or continue to serve the record you have as long as it's still being queried.
