### ISSUE TITLE
--listen --port --upstream pair

### ISSUE THREAD

**Issue by cattyhouse** [AdguardTeam/dnsproxy#274]
### Scenario : 
request on port 5353 will use upstream 8.8.8.8
request on port 6363 will use upsteam 1.1.1.1

### Solution : 
Need to start 2 dnsproxy instance:
````
dnsproxy --listen 127.0.0.1 --port 5353 --upstream 8.8.8.8
dnsproxy --listen 127.0.0.1 --port 6363 --upstream 1.1.1.1
````

### Question :
Is it possible to start just **one** instance? if true, what would the syntax be? thanks

**Comment by ameshkov** [comment]
Nope, not possible, you should run two instances for that.
