### ISSUE TITLE
{bug} panic: net/http: internal error: connCount underflow

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#278]
Sep 28 12:59:27 potter dnsproxy[91339]: panic: net/http: internal error: connCount underflow
Sep 28 12:59:27 potter dnsproxy[91339]: goroutine 799711 [running]:
Sep 28 12:59:27 potter dnsproxy[91339]: net/http.(*Transport).decConnsPerHost(0xc026a3c000, {{0x0, 0x0}, {0xc028963d00, 0x5}, {0xc01a26b0e0, 0xd}, 0x0})
Sep 28 12:59:27 potter dnsproxy[91339]:         /usr/local/go/src/net/http/transport.go:1476 +0x592
Sep 28 12:59:27 potter dnsproxy[91339]: net/http.(*Transport).roundTrip(0xc026a3c000, 0xc01c105000)
Sep 28 12:59:27 potter dnsproxy[91339]:         /usr/local/go/src/net/http/transport.go:605 +0x88b
Sep 28 12:59:27 potter dnsproxy[91339]: net/http.(*Transport).RoundTrip(0xc01c105000?, 0xa090c0?)
Sep 28 12:59:27 potter dnsproxy[91339]:         /usr/local/go/src/net/http/roundtrip.go:17 +0x19
Sep 28 12:59:27 potter dnsproxy[91339]: net/http.send(0xc01c104f00, {0xa090c0, 0xc026a3c000}, {0x92f3e0?, 0x4b6c01?, 0xcdaf60?})
Sep 28 12:59:27 potter dnsproxy[91339]:         /usr/local/go/src/net/http/client.go:251 +0x5f7
Sep 28 12:59:27 potter dnsproxy[91339]: net/http.(*Client).send(0xc01d3f9c20, 0xc01c104f00, {0x0?, 0x40e75f?, 0xcdaf60?})
Sep 28 12:59:27 potter dnsproxy[91339]:         /usr/local/go/src/net/http/client.go:175 +0x9b
Sep 28 12:59:27 potter dnsproxy[91339]: net/http.(*Client).do(0xc01d3f9c20, 0xc01c104f00)
Sep 28 12:59:27 potter dnsproxy[91339]:         /usr/local/go/src/net/http/client.go:715 +0x8fc
Sep 28 12:59:27 potter dnsproxy[91339]: net/http.(*Client).Do(...)
Sep 28 12:59:27 potter dnsproxy[91339]:         /usr/local/go/src/net/http/client.go:581
Sep 28 12:59:27 potter dnsproxy[91339]: github.com/AdguardTeam/dnsproxy/upstream.(*dnsOverHTTPS).exchangeHTTPSClient(0xc000030500, 0xc0122c9440, 0xc0122c9440?)
Sep 28 12:59:27 potter dnsproxy[91339]:         /root/dnsproxy/upstream/upstream_doh.go:169 +0x3db
Sep 28 12:59:27 potter dnsproxy[91339]: github.com/AdguardTeam/dnsproxy/upstream.(*dnsOverHTTPS).exchangeHTTPS(0xc000030500, 0xc0242a86c0?)
Sep 28 12:59:27 potter dnsproxy[91339]:         /root/dnsproxy/upstream/upstream_doh.go:144 +0xaa
Sep 28 12:59:27 potter dnsproxy[91339]: github.com/AdguardTeam/dnsproxy/upstream.(*dnsOverHTTPS).Exchange(0xc000030500, 0xc0122c9440)
Sep 28 12:59:27 potter dnsproxy[91339]:         /root/dnsproxy/upstream/upstream_doh.go:106 +0xe5
Sep 28 12:59:27 potter dnsproxy[91339]: github.com/AdguardTeam/dnsproxy/upstream.exchangeAsync({0xa0afa0, 0xc000030500}, 0x10?, 0x0?)
Sep 28 12:59:27 potter dnsproxy[91339]:         /root/dnsproxy/upstream/parallel.go:117 +0x58
Sep 28 12:59:27 potter dnsproxy[91339]: created by github.com/AdguardTeam/dnsproxy/upstream.ExchangeParallel
Sep 28 12:59:27 potter dnsproxy[91339]:         /root/dnsproxy/upstream/parallel.go:45 +0x18c

**Comment by ameshkov** [comment]
谢谢你，我们会想一想，这不是我们的问题，是golang内的bug。不过，我们需要处理这样的，避免崩溃。

@ainar-g what do you think, should we just handle panics in dnsproxy?

**Comment by ameshkov** [comment]
其实，有可能是和 #279 一样的 bug。来我关闭这里的 Issue，请看看 #279 修理后的情况。

**Comment by ameshkov** [comment]
It still happens even after fixing #279?

**Comment by ameshkov** [comment]
哪个 golang 版？

**Comment by ameshkov** [comment]
试试 go 1.18，我想知道是不是 go 1.19.1 的新bug

**Comment by ameshkov** [comment]
没问题，我等

**Comment by ameshkov** [comment]
@Potterli20 谢谢你研究这个问题。请试试用 [fix-278](https://github.com/AdguardTeam/dnsproxy/tree/fix-278) branch 看看是不是修理这个问题。
