### ISSUE TITLE
Configure optimistic cache TTL-value

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/dnsproxy#284]
### **Background**
If a stale record is served to a client and the IP-address have changed for the record, 10 seconds feels like a really long time and could give a timeout error message. Personally I would use 1-2 seconds to get an updated record available faster to the client having connection issues. I have tried to optimize my cache-size to not store too many records, but with this settings you can use a bigger cache since in the case of a changed IP-address it's all solved in 1-2 seconds without the user noticing anything.

### **Solution**
It would be really nice to configure the optimistic cache TTL value through the config-file instead of the hard-coded 10 seconds.

https://github.com/AdguardTeam/dnsproxy/blob/cff45631257465c5e8fbd8753ab54c692f1fb3e0/proxy/cache.go#L108

Low hanging fruit?! :-)

**Comment by ameshkov** [comment]
I'd just like to avoid additional configuration when it's possible.

Are there any cases that we can reproduce when this TTL causes any troubles?

**Comment by ameshkov** [comment]
> Can a stale record live in the cache for days/weeks and is not deleted until the whole cache is filled up or does it respect the "cache-max-ttl" value?

This is a good point, it can live indefinitely given that there were no requests for that domain.
