### ISSUE TITLE
Duvida de Configuração

### ISSUE THREAD

**Issue by AdmsSuporte** [AdguardTeam/dnsproxy#293]
Olá,

Quero fazer uns testes com os tipos de dns em Linux(ubuntu ou debian) com over quic e http/3, sou novo no uso da ferramenta
então queria saber umas coisas como:
1- Eu preciso instalar o adguadhome para usar o dnsproxy?
2 - E aonde posso achar instruções/tutorias/ de com  instalar a ferramenta (adguadhome/dnsproxy) e configurar os dns para os teste.

Obrigado.

**Comment by ameshkov** [comment]
Hi,

1. You don't need AdGuard Home, can just use dnsproxy alone.
2. There are no special instructions save for the repo's README.
