### ISSUE TITLE
http2.GoAwayFrame before a SETTINGS frame

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#300]
http2.GoAwayFrame before a SETTINGS frame
golang http2 Long link problem
https://github.com/AdguardTeam/dnsproxy/blob/master/upstream/upstream_doh.go
https://cs.opensource.google/go/x/net/+/master:http2/server.go

**Comment by ameshkov** [comment]
Could you please add a more detailed explanation of the issue?

**Comment by ameshkov** [comment]
So you're saying that if connection lives long enough to have 10000 control frames go through it, it will be forcibly closed? Did I get it right?

**Comment by ameshkov** [comment]
Sounds like a golang bug again:(

We can limit the connection lifetime (30 minutes for instance) and re-connect forcibly when it expires.

But first I need to be able to reproduce the issue locally. How can I do that?
