### ISSUE TITLE
Clean up the system dns cache after dnsproxy starts successfully

### ISSUE THREAD

**Issue by NPCDW** [AdguardTeam/dnsproxy#305]
I set up two dns addresses, primary dns: 127.0.0.1, and backup dns: 192.168.0.1.

After turning off dnsproxy, the backup dns worked.

When I reopened dnsproxy, some websites were cached by the backup dns , did not pass the main dns.

When I execute the `ipconfig /flushdns` command, the  primary dns started to work.

Proceed as follows:

1. Close dnsproxy, then clear the system cache and open a new inprivate window and visit a website
2. Open dnsproxy
  a. do not clean up the system cache, and then open a new inprivate window
  ![image](https://user-images.githubusercontent.com/32638459/210317929-fe4c2ec4-91a6-4abd-a471-aea21ec8f29d.png)
  b. clear the system cache, open a new inprivate window
  ![image](https://user-images.githubusercontent.com/32638459/210318084-a0b2312c-9d41-46f4-bef9-cbb84e1aaf5d.png)

**Comment by ameshkov** [comment]
I don't think this should be a part of dnsproxy functionality.

Every OS provides a way to clear DNS cache, you should use it in your own scripts.
