### ISSUE TITLE
Cache more record types

### ISSUE THREAD

**Issue by jjp22191-cdfaq** [AdguardTeam/dnsproxy#308]
The cache only seems to cache `A` and `AAAA` record types.

It should be extended to cache all the others (such as `HTTPS`, `SVCB`, etc).

CoreDNS will cache everything except zone transfers and metadata records (https://coredns.io/plugins/cache/#description).

**Comment by ameshkov** [comment]
This issue will be resolved automatically when we switch dnsproxy to the same server implementation AdGuard DNS uses:
https://github.com/AdguardTeam/AdGuardDNS/tree/master/internal/dnsserver

We'll do it when its code is fully stabilized. There're a couple of major changes coming in Q1-Q2 to AdGuard DNS and then we're good to go.

**Comment by jcoetzee** [comment]
Is there an issue/pull request where we can track the progress of this work?

**Comment by ameshkov** [comment]
@jcoetzee no issue at the moment, I'll open a new one when we're ready.
