### ISSUE TITLE
Extend "AddressToUpstream" with dnsmasq-like domain specification

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/dnsproxy#32]
See `--server` here:
http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

> If one or more optional domains are given, that server is used only for those domains and they are queried only using the specified server. This is intended for private nameservers: if you have a nameserver on your network which deals with names of the form xxx.internal.thekelleys.org.uk at 192.168.1.1 then giving the flag --server=/internal.thekelleys.org.uk/192.168.1.1 will send all queries for internal machines to that nameserver, everything else will go to the servers in /etc/resolv.conf. 

> An empty domain specification, // has the special meaning of "unqualified names only" ie names without any dots in them.

> More specific domains take precedence over less specific domains, so: --server=/google.com/1.2.3.4 --server=/www.google.com/2.3.4.5 will send queries for *.google.com to 1.2.3.4, except *www.google.com, which will go to 2.3.4.5

> The special server address '#' means, "use the standard servers", so --server=/google.com/1.2.3.4 --server=/www.google.com/# will send queries for *.google.com to 1.2.3.4, except *www.google.com which will be forwarded as usual.

In our case, we should allow the following format:
```
--upstream=[/[domain1][/../domainN]/]upstreamString
```

**Comment by admitrevskiy** [comment]
Fixed here: https://github.com/AdguardTeam/dnsproxy/commit/743c1bb0b9cf8a30ffa4f3273a9f63fbb9257bff
