### ISSUE TITLE
[error] dnsproxy: unpacking udp packet: dns: overflowing header size when using dnsmasq --use-stale-cache

### ISSUE THREAD

**Issue by cattyhouse** [AdguardTeam/dnsproxy#327]
# STEPS TO REPRODUCE

## on gateway (dhcp server)

1. dnsproxy listens on gateway `-l 0.0.0.0 -p 53888`, dnsmasq listen on 53 and uses dnsproxy as upstream

## on client

1. systemd-networkd

```
[Match]
Name=en*
[Network]
DHCP=yes
```

2. systemd-resolved

```
systemctl enable --now systemd-resolved
ln -rsf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
```

3. resolvectl output

```
...
Current DNS Server: GATEWAY_IP_ADDR
Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
...
```

4. `dig api.github.com`

## on gateway (dhcp server)
log from gateway (dhcp server)

```
...
[error] dnsproxy: unpacking udp packet: dns: overflowing header size 
...
```

**Comment by ameshkov** [comment]
Could you please use tcpdump on gateway and check what exactly is received by dnsproxy?
