### ISSUE TITLE
dnsproxy report error when dnsmasq uses use-stale-cache option

### ISSUE THREAD

**Issue by cattyhouse** [AdguardTeam/dnsproxy#328]
> i feel like this is still an issue worth reporting: 

# `client` definition: 

`the client` who uses gateway's dns services, not the client who runs dnsproxy or dnsmasq

# `gateway` definition:

the machine runs dnsproxy and dnsmasq, to provide dns services

# only reproducable from macOS client

linux client does not have this issue

# on gateway 192.168.1.1 (debian)

1. start dnsmasq on 5353, upstream set to dnsproxy 9999
```
dnsmasq --port=5353 --server='127.0.0.1#9999' --use-stale-cache --no-daemon --filter-AAAA --no-resolv --no-poll --domain-needed --log-queries=extra --log-async  --log-debug --log-facility=- --fast-dns-retry --edns-packet-max=1232
```

2. start dnsproxy on 9999

```
dnsproxy -l 127.0.0.1 -p 9999 -u https://1.1.1.1/dns-query -u https://8.8.8.8/dns-query --ipv6-disabled --all-servers
```

# on macOS client

```
while true ; do dig @192.168.1.1 -p 5353 api.github.com +short ; sleep 10 ; done

# we sleep 10 because api.github.com ttl is around 70s
```

when dnsmasq report after ttl (70s for apt.github.com) expired : 

```
cached-stale api.github.com is 192.30.255.116
forwarded api.github.com to 127.0.0.1#9999
forwarded api.github.com to 127.0.0.1#9999
forwarded api.github.com to 127.0.0.1#9999

# no reply any more
```

dnsproxy report :

```
dnsproxy: unpacking udp packet: dns: overflowing header size
dnsproxy: unpacking udp packet: dns: overflowing header size
dnsproxy: unpacking udp packet: dns: overflowing header size
dnsproxy: unpacking udp packet: dns: overflowing header size
```

## my conclusion

- this means, the first query was ok, cache was ok, but the query after stale-cache, dnsmasq does not get reply from dnsproxy

- change `--server='127.0.0.1#9999'` to `--server='1.1.1.1'` on dnsmasq, it went ok after stale-cache, this means 1.1.1.1 handles dnsmasq query after stale-cache ok. but `dnsproxy does not handle this`
- change dig to other dns tools, same issue. so it is not dig's issue.

# on Linux client and gateway itself

same command `while true ; do dig @192.168.1.1 -p 5353 api.github.com +short ; sleep 10 ; done`

**no issue** found on dnsmasq and dnsproxy.

# dig output difference 

macOS client vs Linux  client after **gateway stale-cache query**

macOS : 

```
; EDNS: version: 0, flags:; udp: 1232
; OPT=15: 00 03 ("..")

```
Linux : 

```

; EDNS: version: 0, flags:; udp: 1232
; EDE: 3 (Stale Answer)

```

# Questions

- i really like the idea of --use-stale-cache from dnsmasq, and i really like dnsproxy as well
- you mentioned tcpdump, what command should i run on tcpdump to get more info?

**Comment by ameshkov** [comment]
thank you for reporting this to us and dnsmasq, glad it got resolved
