### ISSUE TITLE
not correct permissions for created log file

### ISSUE THREAD

**Issue by alvussar** [AdguardTeam/dnsproxy#33]
start dnsproxy with -o /root/edns/debug.log
proccess  creates log file with 0755 permission access

[15:08] root@host ~/edns # stat debug.log
  File: ‘debug.log’
  Size: 1363            Blocks: 8          IO Block: 4096   regular file
Device: ca03h/51715d    Inode: 660706      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-03-04 15:08:00.565400970 +0200
Modify: 2019-03-04 15:07:52.409434027 +0200
Change: 2019-03-04 15:07:52.409434027 +0200
 Birth: -

**Comment by ameshkov** [comment]
@admitrevskiy change to 0644.

Btw, we have the very same issue in AdGuard Home.
