### ISSUE TITLE
Update  quic-go to v0.35.1 and dns to 1.1.54

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#331]
When will quic-go be updated?@EugeneOne1 

https://github.com/quic-go/quic-go

**Comment by EugeneOne1** [comment]
@Potterli20, we're trying to keep the dependencies up-to-date, but it isn't always the highest priority.  So eventually we'll update the `dns` library as well, and you may even create a separate issue about it.
