### ISSUE TITLE
What is required for DNS-over-QUIC to be considered production ready?

### ISSUE THREAD

**Issue by jcoetzee** [AdguardTeam/dnsproxy#334]
The readme has a callout regarding the experimental nature of DNS-over-QUIC functionality
>Note that DNS-over-QUIC support is experimental, don't use it in production.

Is this still true today? If so, out of interest, what work/validation would be required for it to be considered production-ready? I'm asking primarily regarding dnsproxy acting as a DNS-over-QUIC client, not server.

**Comment by ameshkov** [comment]
Well, that's a good question. On one hand, we already use DoQ in production (in AdGuard DNS) and it is de-facto production-ready. On the other hand, the underlying quic-go library is being constantly updated and I wouldn't say it is as stable as Go's crypto/tls. Quic is soon to be added to the Go stdlib and by that time everything should be stable enough.

**Comment by jcoetzee** [comment]
That makes sense. Thanks.
