### ISSUE TITLE
private-rdns-upstream isn't honored

### ISSUE THREAD

**Issue by x86txt** [AdguardTeam/dnsproxy#343]
Hi, I am new to dnsproxy and replacing a working stubby dnsdist config. Everything is working great, but `--private-rdns-upstream` doesn't seem to be honored, as no PTR record resolution occurs through dnsproxy, but resolution is fine if I dig the IP of the specified server itself. All forward name resolution works just fine for my LAN.

10.5.22.5 and 6 = my lan dns servers (Windows Server 2022 DNS)
10.5.22.12 = latest dnsproxy on Ubuntu

Here is the command line I am using to launch dnsproxy:

```
/usr/local/bin/dnsproxy --output=/var/log/dnsproxy/output.log --listen=0.0.0.0 --port=53 --https-port=443 --tls-crt=/etc/letsencrypt/live/x.x.x.x/fullchain.pem --tls-key=/etc/letsencrypt/live/x.x.x.x/privkey.pem --http3 --upstream=https://my.public.dns/url --upstream=[/*.secunit.lan/]10.5.22.5:53 --upstream=[/*.secunit.lan/]10.5.22.6:53 --private-rdns-upstream=10.5.22.5:53 --private-rdns-upstream=10.5.22.6:53 --ipv6-disabled --edns
```

here is my LAN DNS server queried directly:

```
dig -x 10.5.22.6 @10.5.22.6 +short
dc1.secunit.lan.
```

If I execute a dig or nslookup against the dnsproxy, I get an NXDOMAIN:

```
dig -x 10.5.22.6 @10.5.22.12
opcode: QUERY, status: NXDOMAIN, id: 35020
6.22.5.10.in-addr.arpa.                IN      PTR

AUTHORITY SECTION:
10.in-addr.arpa.        2286    IN      SOA     prisoner.iana.org. hostmaster.root-servers.org. 1 604800 60 604800 604800
```

**Comment by x86txt** [comment]
Specifying the upstream in-addr.arpa worked perfectly, thanks for the tip!

**Comment by x86txt** [comment]
Also, I took your advice @EugeneOne1 and moved everything to a config.yaml file. Is it documented in a more thorough way somewhere other than the link you sent? I had to go through quite a bit of trial-and-error, but I got it. If not, I'd be happy to submit a PR with some additional clarification for the config syntax?

**Comment by EugeneOne1** [comment]
@x86txt, hello and apologies for late response.  The thing is that the YAML configuration essentially mirrors the command line options, so the [Usage](https://github.com/AdguardTeam/dnsproxy#usage) section of `README.md`, as well as the output of the `./dnsproxy --help` command, are fully applicable to the configuration file.  The only exception, is the `--config-path` option, which specifies the file itself.

However, you may have noticed that some of the field names differ from the corresponding options, which could be a PR-worthy issue.  I'm not really sure on where it should be documented.  @ameshkov, perhaps, we may fill the configuration file with all the stubs and put this info there?
