### ISSUE TITLE
Can't build today from "master"

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/dnsproxy#348]
I tried to build today as I always have done from "master", but now it gives me a bunch of errors. Anything changed or new prerequisites needed to build?! I'm using Go 1.21.0 on Ubuntu 23.04 and successfully build with it a few days ago from "master".

`env GOOS=linux GOARCH=arm64 make build`

### Output
```
env BRANCH="$( git rev-parse --abbrev-ref HEAD )" COMMIT='' DIST_DIR='build' GO="${GO:-go}" GOAMD64='v1' GOPROXY='https://goproxy.cn|https://proxy.golang.org|direct' OUT='dnsproxy' PATH="${PWD}/bin:$( "${GO:-go}" env GOPATH )/bin:${PATH}" RACE='0' REVISION="$( git rev-parse --short HEAD )" VERBOSE="${VERBOSE:-0}" VERSION="0"           "/bin/sh" ./scripts/make/go-deps.sh

fatal: not a git repository (or any of the parent directories): .git

fatal: not a git repository (or any of the parent directories): .git

env BRANCH="$( git rev-parse --abbrev-ref HEAD )" COMMIT='' DIST_DIR='build' GO="${GO:-go}" GOAMD64='v1' GOPROXY='https://goproxy.cn|https://proxy.golang.org|direct' OUT='dnsproxy' PATH="${PWD}/bin:$( "${GO:-go}" env GOPATH )/bin:${PATH}" RACE='0' REVISION="$( git rev-parse --short HEAD )" VERBOSE="${VERBOSE:-0}" VERSION="0"           "/bin/sh" ./scripts/make/go-build.sh

fatal: not a git repository (or any of the parent directories): .git

fatal: not a git repository (or any of the parent directories): .git

fatal: not a git repository (or any of the parent directories): .git

make: *** [Makefile:49: go-build] Error 128
```

**Comment by EugeneOne1** [comment]
It seems that for some reason the cloned repository doesn't contain the `.git' directory.  We'll think about adding some default values for the environment variables, but it's also possible to run the Makefile scripts setting the required variables manually.  In case of c060c2a788d961f9291afc93d7954022fc52b2e3, this is the actual command:

```sh
make REVISION='c060c2a' BRANCH='master' SOURCE_DATE_EPOCH='1692367359' build
```

**Comment by guillaume-uH57J9** [comment]
I have noticed the same issue when downloading the latest dnsproxy (ie 0.59) from the release page on  github. 
Please consider reopening. 

The [release page](https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.59.0) include a link to download [Source code (tar.gz)](https://github.com/AdguardTeam/dnsproxy/archive/refs/tags/v0.59.0.tar.gz). 

If git clone is required to build the software, consider removing this link from the release page to avoid confusion.
