### ISSUE TITLE
DNS64 config option causes segfault

### ISSUE THREAD

**Issue by suffieldacademy** [AdguardTeam/dnsproxy#350]
Was trying out the DNS64 configuration and noticed the process kept crashing on startup.  Thought it was an issue with my YAML but realized it was the dns64 config option.  Even the command-line argument causes it to crash:

```
dnsproxy --upstream=::1 --bootstrap=::1 --dns64
2023/09/06 15:25:54 [info] Starting dnsproxy v0.54.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8c3546]

goroutine 1 [running]:
main.initDNS64(0xc00013f628, 0xc0000bb8c0?)
	github.com/AdguardTeam/dnsproxy/main.go:569 +0x46
main.createProxyConfig(_)
	github.com/AdguardTeam/dnsproxy/main.go:344 +0x22d
main.run(0xc0000bb8c0)
	github.com/AdguardTeam/dnsproxy/main.go:258 +0x1c7
main.main()
	github.com/AdguardTeam/dnsproxy/main.go:237 +0x44f
```

**Comment by EugeneOne1** [comment]
@suffieldacademy, hello again.  Could you please try the master version now?  It should fix this exact validation step, additionally requiring the `--private-rdns-upstream` option, see the [README.md](https://github.com/AdguardTeam/dnsproxy#dns64-server).

**Comment by suffieldacademy** [comment]
Just compiled and tried it, looks much better!  Not sure of the ticket etiquette here (do you close issues or do I?) so happy to close this if you're ready.

Thanks for the quick fix.

**Comment by EugeneOne1** [comment]
@suffieldacademy, closing the issue you've opened is appreciated.  Thanks.
