### ISSUE TITLE
DNSProxy Listens only on IPV6 [Android]

### ISSUE THREAD

**Issue by kooroshh** [AdguardTeam/dnsproxy#36]
setting listenAddr to 0.0.0.0 on android doesn't work for ipv4 
for ipv4 i have to set the exact ip  !

Code : 
```
Config cfg = new Config();
cfg.setListenPort(7053);
cfg.setListenAddr("0.0.0.0");
proxy.setConfig(cfg);
proxy.start();
```

Logs : 
```
2019-03-10 16:46:40.687 10740-10876/in.test.my I/GoLog: [info] Entering the UDP listener loop on [::]:7053
2019-03-10 16:46:40.687 10740-10876/in.test.my I/GoLog: [info] Entering the tcp listener loop on [::]:7053
```

Netstat : 
```
daisy_sprout:/ $ netstat -an | grep 7053
tcp6       0      0 :::7053                 :::*                    LISTEN
udp6       0      0 :::7053                 :::*
```

**Comment by ameshkov** [comment]
The output of netstat does not mean it does not listen to IPv4, it just listens to both IPv4 and IPv6.

Have you tried actually connecting to `127.0.0.1:7053`?

**Comment by kooroshh** [comment]
yes , connection getting refused with 127.0.0.1 / 192.168.1.51 but with my lan ipv6 works fine

**Comment by ameshkov** [comment]
It seems that this is a standard Golang behavior, it transforms `0.0.0.0` to `::` which, in theory, covers both IPv4 and IPv6 (unless `net.ipv6.bindv6only` is set). Maybe, in your case, it is set?

**Comment by sfionov** [comment]
https://github.com/golang/go/issues/7411
https://github.com/golang/go/issues/12579
It is standard behaviour for "tcp" socket in Golang, but in second issue it is stated that, with bindv6only, 0.0.0.0 should listen to ipv4 only (does it happen actually?). Also stated, that "tcp4" forces ipv4-only socket.

**Comment by kooroshh** [comment]
sorry
it seems the problem is not related to dnsproxy 
it's related to Tun2Socks program which proxify dnsproxiy requests through it's proxy that's why it wont work , 
thanks anyway
