### ISSUE TITLE
0.57.1 build broken

### ISSUE THREAD

**Issue by coolsantino** [AdguardTeam/dnsproxy#362]
![изображение](https://github.com/AdguardTeam/dnsproxy/assets/920767/5e7b2f66-d166-4667-aec9-f490e5db2667)

**Comment by EugeneOne1** [comment]
@coolsantino, thanks for the report, we're working on it.

**Comment by ainar-g** [comment]
I've filed xresloader/upload-to-github-release#57.  @EugeneOne1, in the meantime, please pin the previous version and try to build a new patch.

**Comment by EugeneOne1** [comment]
@coolsantino, FYI, we deleted the `v0.57.1` release and released the identical `v0.57.2`.
