### ISSUE TITLE
Duplicate DNS-queries with v0.61.0

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/dnsproxy#370]
I'm seeing duplicate DNS-queries with v0.61.0 and it seems to query two upstream servers for every DNS-request.

The release note says something about "imp load balance". Is this a new feature trying to do some load-balancing between the upstreams?! Seems like it's not working for me and the same query is forwarded to two upstream servers. All worked fine with v0.60.1 and before.

I'm not using "all-servers" or  "fastest-addr", so just want DNSProxy to use my fastest (RTT) upstream.

![Screenshot from 2023-12-18 18-33-08](https://github.com/AdguardTeam/dnsproxy/assets/52280788/0753c2af-e767-4965-a6fa-58f8551101d9)

**Comment by ameshkov** [comment]
Could you please enable verbose logging in dnsproxy and see if it actually sends duplicate queries?

**Comment by EugeneOne1** [comment]
@iJorgen, well, it seems that there are actually no "duplicate" queries, all these similar requests have different types and are used for different purposes in DNS.  AFAIK, both `A` and `AAAA` as well as `HTTPS` are normally sent by the majority of modern browsers to get as much information as possible about the host.  Are you sure this wasn't the case in earlier versions?  Could you please try to capture such logs with `v0.60.1` for example?

**Comment by EugeneOne1** [comment]
@iJorgen, sorry for not asking this at the beginning, but where do these "duplicates" appear?  I mean, since dnsproxy now chooses the server randomly, probing server's RTT, it's competely possible to choose the same fastest server several times in a row for consequent requests.

**Comment by EugeneOne1** [comment]
@iJorgen, hello again.  Resource records of type 65 (HTTPS) are completely useful in different DNS scenarios, like [DDR](https://datatracker.ietf.org/doc/rfc9462).  Consider using [AdGuard Home](https://github.com/AdguardTeam/AdGuardHome) for filtering such records more precisely.

For now, I suppose this issue may be closed.
