### ISSUE TITLE
Is it possible to block a list of hosts via a file?

### ISSUE THREAD

**Issue by vukitoso** [AdguardTeam/dnsproxy#392]
Hello.
Is it possible to block a list of hosts via a file?
I have my own list of hosts that need to be blocked, for example, give ip 127.0.0.2 or another for a given domain.
Is it possible to do this?
If not, then I suggest adding such functionality.

**Comment by ameshkov** [comment]
Hello, dnsproxy is supposed to be purely a proxy with minimum additional features. All the filtering functionality is available in AdGuard Home which uses `dnsproxy` as a library.
