### ISSUE TITLE
Has v0.67.0 been fixed/changed?!

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/dnsproxy#394]
All files/folders in the latest ZIP source-file are dated back to March 28. Has something really been fixed in v0.67.0 compared to v0.66.1 or has something gone wrong in this build?! Seems like it's the same "master" as 5 days ago.

**Comment by ainar-g** [comment]
As mentioned in the release notes, v0.66.1 has been tagged incorrectly, as there were breaking changes, so that release was removed and reolaced with v0.67.0.  Thanks for being on the lookout thought, heh.
