### ISSUE TITLE
does upstream.Upstream is  goroutine safe

### ISSUE THREAD

**Issue by Nyx2022** [AdguardTeam/dnsproxy#403]
as the title, i wanna know if the upstream.Upstream is  goroutine safe?

**Comment by EugeneOne1** [comment]
@Nyx2022, helllo.  Yes, the `upstream.Upstream` implementations are designed to be safe for concurrent use, in 50640fb5f7b417bcf40eda32500df7173c22977c we've updated the documentation of the interface to reflect the contract.
