### ISSUE TITLE
Add arm and arm64 builds

### ISSUE THREAD

**Issue by cutemanworking** [AdguardTeam/dnsproxy#41]
how can i complie a version for orange pi with armv8 cpu?

**Comment by ameshkov** [comment]
Try something like this:
`GOOS=linux GOARCH=arm GOARM=6 make release`

I guess we should add ARM builds to releases.

**Comment by cutemanworking** [comment]
many thanks!!!

**Comment by ameshkov** [comment]
Plz don't close, we'll add these builds to official releases as a part of this issue
