### ISSUE TITLE
using --hosts-files=./path gives invalid argument error

### ISSUE THREAD

**Issue by juantascon** [AdguardTeam/dnsproxy#418]
* how to reproduce:

echo "10.10.10.10 somehost" >> path
dnsproxy --hosts-files=./path

* error msg:

2024/09/10 13:30:09.174559 INFO dnsproxy starting version=0.73.1 revision="" branch="" commit_time=""
2024/09/10 13:30:09.174606 ERROR running dnsproxy err="configuring proxy: creating default handler: open ./path: invalid argument"

**Comment by s1sw** [comment]
DNSProxy prepends a slash to the path, so you need the full path without a leading slash. For example, if you're in `/home/whoever`, you would need `--hosts-files=home/whoever/path`.

**Comment by alxistr** [comment]
> DNSProxy prepends a slash to the path
But why? I've encountered this too and it's confusing.

> For example, if you're in /home/whoever, you would need --hosts-files=home/whoever/path.
In other words the path is always considered absolute (a current directory doesn't matter) and a leading slash has to be omitted?

**Comment by raystubbs** [comment]
How does this work on windows?  I've run into this, and not sure how to get around it if a slash is prepended to, say, `c:\\blah`.  I've tried several variations (omitting `c:\\`, using the WSL style path `/mtn/c/...`, etc) with no luck.

**Comment by raystubbs** [comment]
Scratch that, I've found the way: for `c:\something\other\hosts` use `something/other/hosts`; it seems the 'root' in this case is C drive.

**Comment by ainar-g** [comment]
This seems to be an error in how paths are handled in relation to the root filesystem.

@schzhn, please investigate.  I feel like Windows paths in particular might pose an issue.

**Comment by schzhn** [comment]
dnsproxy `v0.74.0` now supports both absolute paths and paths relative to the current directory.
