### ISSUE TITLE
listen-addrs and log verbosity

### ISSUE THREAD

**Issue by kemelzaidan** [AdguardTeam/dnsproxy#423]
My dnsproxy config file used to have the `listen-addrs` directive configured to `0.0.0.0`, but recently, I'm configuring my LAN to use IPv6 without NAT, so, before trying to add a restriction to IPv6 I tought it would be interesting to test it with IPv4. So I changed the `listen-addrs` to `192.168.0.0` thinking that I would need to pass the network mask in order for the app to listen only queries from the local network.

But dnsproxy didn't start... :cry: Anyway, I switched back IPv4 to `0.0.0.0` and tried to configure the IPv6 link-local address to `fe80::` but once again, the app didn't start... 

So I wonder how I configure this directive to restrict the queries to the local network only, specially for the IPv6 addresses, but not only them.

In order to debug this, I also configured the `output` directive to `/var/log/dnsproxy.log`, so I could understand what was going on. But I could not find anywhere in the documentation if there is flag for dnsproxy to log only errors and/or warnings.

Thanks for all the help.

**Comment by ameshkov** [comment]
dnsproxy does not support listening to a subnet, only to a specific IP address like `192.168.0.1`.

`0.0.0.0` is the only exception which is provided by the OS itself and it basically means "listen to all network interfaces".
