### ISSUE TITLE
etc/hosts: no such file or directory

### ISSUE THREAD

**Issue by schzhn** [AdguardTeam/dnsproxy#430]
The latest release, `v0.74.0`, contains a bug related to resolving the system hosts file.

As a workaround, you can use the `--hosts-files` command-line flag.
On Unix systems, use `--hosts-files=/etc/hosts`, and on Windows systems, use `--hosts-files="C:\Windows\System32\Drivers\etc\hosts"`.

**Comment by LucaLin233** [comment]
Hi, I'm having the same problem but I'm using docker compose to start dnsproxy and I'm using the config file, how should I fix it?

**Comment by johspa933** [comment]
I'm also using docker compose with dnsproxy and need a solution to fix this issue.

**Comment by schzhn** [comment]
Fixed in `v0.74.1`.
