### ISSUE TITLE
Add DNSCrypt support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/dnsproxy#44]
DNSCrypt seems to be better from the performance point of view, and this might be important to mobiles. So we should considering adding full DNSCrypt support to dnsproxy (and therefore, to AdGuard Home).

**Comment by no-replies** [comment]
There is no vote option.

**Comment by evilvibes** [comment]
Give it a thumbs up! Lol

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ibksturm** [comment]
vote +1

**Comment by no-replies** [comment]
Please add dnscrypt v2 downstream
And upstream

**Comment by ameshkov** [comment]
Yeah, this is a proper issue btw. We should mirror it in AdGuard Home repo.
