### ISSUE TITLE
x509: cannot validate certificate for 89.233.43.71 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by hongyi-zhao** [AdguardTeam/dnsproxy#55]
Hi,

I use dnsproxy to connect to the tls server given here:

https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers

Say, as follows:

dnsproxy -l 127.0.0.1 -p 6666 -s -v -u tls://89.233.43.71

But, I meet the following error:

----------------
2019/08/19 13:56:53 32772#88 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleUDPPacket(): error handling DNS (udp) request: talking to dnsUpstream failed, cause: Failed to get a connection from TLSPool to 89.233.43.71:853, cause: Failed to connect to 89.233.43.71, cause: x509: cannot validate certificate for 89.233.43.71 because it doesn't contain any IP SANs
------------------

How to solve this issue?

Regards

**Comment by ameshkov** [comment]
Well, technically, this test server uses an invalid certificate - it must contain it's IP address in the sub alt names field.
