### ISSUE TITLE
dnsproxy will crash when using multiple ''sdns://'' form upstreams, the info: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hongyi-zhao** [AdguardTeam/dnsproxy#56]
Hi,

I use the dnsproxy with the upsteams set by using multiple dns stamps, at the same time, I also use the  parallel queries with `-s' option.  

But, I found that the dnsproxy will crash, when the number of upsteams > 20.  see the following for more infomation:

------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x653111]

goroutine 525 [running]:
github.com/miekg/dns.(*Msg).IsEdns0(0xc00021a510, 0x78)
	/home/werner/go/pkg/mod/github.com/miekg/dns@v1.1.8/defaults.go:153 +0x61
github.com/ameshkov/dnscrypt.(*Client).adjustPayloadSize(0xc0003080a0, 0xc00021a510)
	/home/werner/go/pkg/mod/github.com/ameshkov/dnscrypt@v1.0.7/dnscrypt.go:227 +0x40
github.com/ameshkov/dnscrypt.(*Client).ExchangeConn(0xc0003080a0, 0xc00021a510, 0xc000326180, 0x9d1840, 0xc0006e0020, 0xc00039a010, 0xd, 0x9d1840, 0xc0006e0020)
	/home/werner/go/pkg/mod/github.com/ameshkov/dnscrypt@v1.0.7/dnscrypt.go:166 +0x832
github.com/ameshkov/dnscrypt.(*Client).Exchange(0xc0003080a0, 0xc00021a510, 0xc000326180, 0x0, 0x0, 0x0, 0x0)
	/home/werner/go/pkg/mod/github.com/ameshkov/dnscrypt@v1.0.7/dnscrypt.go:151 +0x19c
github.com/AdguardTeam/dnsproxy/upstream.(*dnsCrypt).Exchange(0xc000182c90, 0xc00021a510, 0x0, 0x0, 0x0)
	/home/werner/dnsproxy.git/upstream/upstream_dnscrypt.go:55 +0x1cd
github.com/AdguardTeam/dnsproxy/upstream.exchangeAsync(0x9c7980, 0xc000182c90, 0xc00021a510, 0xc0008124e0)
	/home/werner/dnsproxy.git/upstream/parallel.go:67 +0x3f
created by github.com/AdguardTeam/dnsproxy/upstream.ExchangeParallel
	/home/werner/dnsproxy.git/upstream/parallel.go:41 +0xd4
werner@localhost:~/software/anti-gfw/dns/doh-dot-dnscrypt/dnsproxy$ 
------------------------
 
I started the dnsproxy with the following command:

------------
./dnsproxy -l 127.0.0.1 -p $port -s -v -u sdns://AQcAAAAAAAAADjIxMi40Ny4yMjguMTM2IOgBuE6mBr-wusDOQ0RbsV66ZLAvo8SqMa4QY2oHkDJNHzIuZG5zY3J5cHQtY2VydC5mci5kbnNjcnlwdC5vcmc \
-u sdns://AQcAAAAAAAAAEzE0Ni4xODUuMTY3LjQzOjUzNTMg9J8sc01itoYxntB-aRlDOy8ThfQe-8ovF21ZCy5FPoYcMi5kbnNjcnlwdC1jZXJ0LnNlY3VyZWRucy5ldQ \
-u sdns://AgcAAAAAAAAADjE0Ni4xODUuMTY3LjQzID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4EGRvaC5zZWN1cmVkbnMuZXUKL2Rucy1xdWVyeQ \
-u sdns://AQMAAAAAAAAADzE2My4xNzIuMTgwLjEyNSDfYnO_x1IZKotaObwMhaw_-WRF1zZE9mJygl01WPGh_x8yLmRuc2NyeXB0LWNlcnQuc2Z3LnNjYWxld2F5LWZy \
-u sdns://AQcAAAAAAAAAFDE3OC4yMTYuMjAxLjIyMjoyMDUzICXE4YgpFUaXj5wrvbanr6QB7aBRBQhdUwPnGSjAZo8hHTIuZG5zY3J5cHQtY2VydC5zb2x0eXNpYWsuY29t \
-u sdns://AQcAAAAAAAAAEjE2My4xNzIuMTM1LjkxOjQ0MyAa1c2tko5PA1_fBzSXfz3pIB-3QKK04gA99gF7D_ePqBwyLmRuc2NyeXB0LWNlcnQuZnIuc3VhbWkuY29t \
-u sdns://AQcAAAAAAAAADTEwNy4xNzAuNTcuMzQg6YXxGK1OPMZf8iUgGJDG9Vi3W1pS9WsXz-rBAFyLm6olMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LnZlbnRyaWNsZS51cw \
-u sdns://AQQAAAAAAAAAEDc3Ljg4LjguNzg6MTUzNTMg04TAccn3RmKvKszVe13MlxTUB7atNgHhrtwG1W1JYyciMi5kbnNjcnlwdC1jZXJ0LmJyb3dzZXIueWFuZGV4Lm5ldA \
-u sdns://AQYAAAAAAAAAETE1MS44MC4yMjIuNzk6NDQzIO4Y9lZnORlvodxu39dnm6mFruwTRnlmovbEga4Fyw3TIDIuZG5zY3J5cHQtY2VydC5vcGVubmljLmkycGQueHl6 \
-u sdns://AQMAAAAAAAAAEjE0OS4xMTIuMTEyLjk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0 \
-u sdns://AQYAAAAAAAAADTkuOS45LjEwOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA \
-u sdns://AQYAAAAAAAAAEzE0OS4xMTIuMTEyLjEwOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA \
-u sdns://AgMAAAAAAAAABzkuOS45LjmAABJkbnM5LnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ \
-u sdns://AgMAAAAAAAAADTE0OS4xMTIuMTEyLjmAABJkbnM5LnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ \
-u sdns://AgYAAAAAAAAACDkuOS45LjEwgAASZG5zOS5xdWFkOS5uZXQ6NDQzCi9kbnMtcXVlcnk \
-u sdns://AgYAAAAAAAAADjE0OS4xMTIuMTEyLjEwgAASZG5zOS5xdWFkOS5uZXQ6NDQzCi9kbnMtcXVlcnk \
-u sdns://AQcAAAAAAAAAEjE3My44Mi4yMzIuMjMyOjg1MyCPlK_22Cu9WRVyKgl-CZp2GXezsRDWizG-BHIzChok4iAyLmRuc2NyeXB0LWNlcnQucXVhbGl0eW9sb2d5LmNvbQ \
-u sdns://AgUAAAAAAAAAACA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OBJlYS1kbnMucnVieWZpc2guY24KL2Rucy1xdWVyeQ \
-u sdns://AgUAAAAAAAAAACA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OBJ1dy1kbnMucnVieWZpc2guY24KL2Rucy1xdWVyeQ \
-u sdns://AQcAAAAAAAAADjIxMi40Ny4yMjguMTM2IOgBuE6mBr-wusDOQ0RbsV66ZLAvo8SqMa4QY2oHkDJNHzIuZG5zY3J5cHQtY2VydC5mci5kbnNjcnlwdC5vcmc \
-u sdns://AQcAAAAAAAAAEzE0Ni4xODUuMTY3LjQzOjUzNTMg9J8sc01itoYxntB-aRlDOy8ThfQe-8ovF21ZCy5FPoYcMi5kbnNjcnlwdC1jZXJ0LnNlY3VyZWRucy5ldQ \
-u sdns://AgcAAAAAAAAADjE0Ni4xODUuMTY3LjQzID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4EGRvaC5zZWN1cmVkbnMuZXUKL2Rucy1xdWVyeQ \
-u sdns://AQMAAAAAAAAADzE2My4xNzIuMTgwLjEyNSDfYnO_x1IZKotaObwMhaw_-WRF1zZE9mJygl01WPGh_x8yLmRuc2NyeXB0LWNlcnQuc2Z3LnNjYWxld2F5LWZy \
-u sdns://AQcAAAAAAAAAFDE3OC4yMTYuMjAxLjIyMjoyMDUzICXE4YgpFUaXj5wrvbanr6QB7aBRBQhdUwPnGSjAZo8hHTIuZG5zY3J5cHQtY2VydC5zb2x0eXNpYWsuY29t \
-u sdns://AQcAAAAAAAAAEjE2My4xNzIuMTM1LjkxOjQ0MyAa1c2tko5PA1_fBzSXfz3pIB-3QKK04gA99gF7D_ePqBwyLmRuc2NyeXB0LWNlcnQuZnIuc3VhbWkuY29t \
-u sdns://AQcAAAAAAAAADTEwNy4xNzAuNTcuMzQg6YXxGK1OPMZf8iUgGJDG9Vi3W1pS9WsXz-rBAFyLm6olMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LnZlbnRyaWNsZS51cw \
-u sdns://AQQAAAAAAAAAEDc3Ljg4LjguNzg6MTUzNTMg04TAccn3RmKvKszVe13MlxTUB7atNgHhrtwG1W1JYyciMi5kbnNjcnlwdC1jZXJ0LmJyb3dzZXIueWFuZGV4Lm5ldA \
-u sdns://AQYAAAAAAAAAETE1MS44MC4yMjIuNzk6NDQzIO4Y9lZnORlvodxu39dnm6mFruwTRnlmovbEga4Fyw3TIDIuZG5zY3J5cHQtY2VydC5vcGVubmljLmkycGQueHl6
------------

How to solve this issue?

Regards

**Comment by ameshkov** [comment]
Most likely the problem is triggered by one of the upstreams. Could you please try removing upstreams one by one to see which one triggers this?

**Comment by hongyi-zhao** [comment]
Andrey Meshkov <notifications@github.com> 于2019年8月19日周一 下午4:11写道：

> Most likely the problem is triggered by one of the upstreams. Could you
> please try removing upstreams one by one to see which one triggers this?
>

NO,  I tried with only using two upstreams like the following:

$ dnsproxy -l 127.0.0.1 -p 6666 -s -v -u
sdns://AQcAAAAAAAAADjIxMi40Ny4yMjguMTM2IOgBuE6mBr-wusDOQ0RbsV66ZLAvo8SqMa4QY2oHkDJNHzIuZG5zY3J5cHQtY2VydC5mci5kbnNjcnlwdC5vcmc
\
-u
sdns://AQcAAAAAAAAAEzE0Ni4xODUuMTY3LjQzOjUzNTMg9J8sc01itoYxntB-aRlDOy8ThfQe-8ovF21ZCy5FPoYcMi5kbnNjcnlwdC1jZXJ0LnNlY3VyZWRucy5ldQ

Then, I using a very frequent dig to invoke it, this will trigger the crash
within about several seconds:

$ while :; do dig www.twitter.com -p6666 | grep 'Query time' ; sleep 0.001
; done
;; Query time: 440 msec
;; Query time: 188 msec
;; Query time: 238 msec
;; Query time: 253 msec
;; Query time: 183 msec
;; Query time: 247 msec
;; Query time: 247 msec
;; Query time: 179 msec
;; Query time: 179 msec
;; Query time: 199 msec
;; Query time: 179 msec
;; Query time: 208 msec
;; Query time: 212 msec
;; Query time: 182 msec
;; Query time: 216 msec
;; Query time: 175 msec
;; Query time: 316 msec
;; Query time: 244 msec
;; Query time: 382 msec
;; Query time: 319 msec
;; Query time: 169 msec
;; Query time: 313 msec
;; Query time: 182 msec
;; Query time: 178 msec
;; Query time: 209 msec
;; Query time: 253 msec
;; Query time: 190 msec
;; Query time: 240 msec
;; Query time: 255 msec
;; Query time: 397 msec
;; Query time: 191 msec
;; Query time: 247 msec
;; Query time: 178 msec
;; Query time: 173 msec
;; Query time: 195 msec
;; Query time: 185 msec
;; Query time: 177 msec
;; Query time: 178 msec
;; Query time: 257 msec
;; Query time: 380 msec

crashed.


With the following info:

--------------------
panic: runtime error: index out of range

goroutine 144 [running]:
github.com/miekg/dns.(*Msg).IsEdns0(0xc0003943f0, 0x78)
/home/werner/go/pkg/mod/github.com/miekg/dns@v1.1.8/defaults.go:154 +0xf8
github.com/ameshkov/dnscrypt.(*Client).adjustPayloadSize(0xc00000ede0,
0xc0003943f0)
/home/werner/go/pkg/mod/github.com/ameshkov/dnscrypt@v1.0.7/dnscrypt.go:227
+0x40
github.com/ameshkov/dnscrypt.(*Client).ExchangeConn(0xc00000ede0,
0xc0003943f0, 0xc00013ee80, 0x9d1840, 0xc000214140, 0xc000028dc0, 0x12,
0x9d1840, 0xc000214140)
/home/werner/go/pkg/mod/github.com/ameshkov/dnscrypt@v1.0.7/dnscrypt.go:166
+0x832
github.com/ameshkov/dnscrypt.(*Client).Exchange(0xc00000ede0, 0xc0003943f0,
0xc00013ee80, 0x0, 0x0, 0x0, 0x0)
/home/werner/go/pkg/mod/github.com/ameshkov/dnscrypt@v1.0.7/dnscrypt.go:151
+0x19c
github.com/AdguardTeam/dnsproxy/upstream.(*dnsCrypt).Exchange(0xc0001808d0,
0xc0003943f0, 0x2c, 0x9c82c0, 0xc00035b1a0)
/home/werner/dnsproxy.git/upstream/upstream_dnscrypt.go:55 +0x1cd
github.com/AdguardTeam/dnsproxy/upstream.exchangeAsync(0x9c7980,
0xc0001808d0, 0xc0003943f0, 0xc0002c87e0)
/home/werner/dnsproxy.git/upstream/parallel.go:67 +0x3f
created by github.com/AdguardTeam/dnsproxy/upstream.ExchangeParallel
/home/werner/dnsproxy.git/upstream/parallel.go:41 +0xd4
----------------------

You can try to see whether or not to duplicate this bug.

Regards
-- 
Hongsheng Zhao <hongyi.zhao@gmail.com>
Institute of Semiconductors, Chinese Academy of Sciences
GnuPG DSA: 0xD108493

**Comment by ameshkov** [comment]
@szolin I bet the issue is caused by the rate limiter.

It seems that in some conditions we are passing `nil` instead of the `dns.Msg` to the upstream.

**Comment by szolin** [comment]
I've reproduced it with `panic: runtime error: index out of range` error on line 154.  This clearly indicates that it's a race condition.

**Comment by szolin** [comment]
The problem is in this code in dnscrypt:
```
func (c *Client) adjustPayloadSize(msg *dns.Msg) {
...
		msg.SetEdns0(uint16(maxPayloadSize), dnssec)
```

We modify the original DNS request object, instead of modifying a copy.
