### ISSUE TITLE
Some questions on using `-b, --bootstrap=' option.

### ISSUE THREAD

**Issue by hongyi-zhao** [AdguardTeam/dnsproxy#58]
Hi,

I have some questions on using the `-b, --bootstrap=' option:

[1]  The help said:

-b, --bootstrap=   Bootstrap DNS for DoH and DoT, can be specified multiple
                     times (default: 8.8.8.8:53)

Is said this is only for DoH and DoT, why not for dnscrypt?

[2]  If I have one of the upstreams setting by the ip instead of hostname, then can this one be used for bootstraping other ones using hostname?   I mean, in this case, can I not use the bootstrap dns?

Regards

**Comment by ameshkov** [comment]
> Is said this is only for DoH and DoT, why not for dnscrypt?

Dnscrypt does not rely on domain names so there's no need to resolve anything before using it

> If I have one of the upstreams setting by the ip instead of hostname, then can this one be used for bootstraping other ones using hostname? I mean, in this case, can I not use the bootstrap dns?

Yes, you can use a DNS stamp with a server IP baked into the stamp. In this case, dnsproxy will use this IP instead of trying to resolve the hostname.
