### ISSUE TITLE
Makefile:29: recipe for target 'test' failed

### ISSUE THREAD

**Issue by hongyi-zhao** [AdguardTeam/dnsproxy#60]
Hi,

I try to do the `make' but failed with the following [excerpted] error:

---------------
      upstream_test.go:374: Couldn't talk to upstream https://dns.google/dns-query: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns.google:443/dns-query', cause: Get https://dns.google:443/dns-query?dns=DEABAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
 [snipped]
       upstream_test.go:374: Couldn't talk to upstream https://1.1.1.1/dns-query: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://1.1.1.1:443/dns-query', cause: Get https://1.1.1.1:443/dns-query?dns=BU8BAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
 [snipped]
FAIL
exit status 1
FAIL	github.com/AdguardTeam/dnsproxy/upstream	157.794s
FAIL
Makefile:29: recipe for target 'test' failed
make: *** [test] Error 1
--------------

But, the `go build' will success.

How to solve this issue?

Regards

**Comment by ameshkov** [comment]
Well, you can simply comment the tests out:
https://github.com/AdguardTeam/dnsproxy/blob/master/Makefile#L29
