### ISSUE TITLE
How to let dnsproxy give the best ip addresses?

### ISSUE THREAD

**Issue by hongyi-zhao** [AdguardTeam/dnsproxy#64]
Hi,

See my following testing:

I let dnsproxy listen on 6053 port.

```
$ dig +short -p 6053 github.com
13.229.188.59
```

But the https://github.com.ipaddress.com/  gives the following result:
140.82.113.4

Any hints?

**Comment by ameshkov** [comment]
Github uses geo-DNS so the answer depends on the user's location.

**Comment by hongyi-zhao** [comment]
But I run both methods from the same location.  Still confused on this issue.

**Comment by ameshkov** [comment]
No, the second one works from the location of the `ipaddress.com` server

**Comment by hongyi-zhao** [comment]
Even so, I still cannot figure out the following issue:

When I  access the https://github.com.ipaddress.com/ via different socks proxy,  it will gives the same results:


Case 1:

```
What Is My IP:
India Flag157.245.109.209

Domain Summary
7.1 Million / Day
34.3 Million / Day
October 9, 2007
11 years, 11 months and 22 days (4,375 days)
140.82.113.4
United States

```

Case 2:

```
What Is My IP:
Germany Flag134.209.255.238

Domain Summary
7.1 Million / Day
34.3 Million / Day
October 9, 2007
11 years, 11 months and 22 days (4,375 days)
140.82.113.4
United States
```

You can see, it will give the same query result: 140.82.113.4

Any hints?

**Comment by ameshkov** [comment]
Your location does not matter, what matters is the location of the ipaddress websites' server

**Comment by hongyi-zhao** [comment]
Thanks for your reply.

I ask this issue is due to the following problem I'm meeting:

When using the dnsproxy to query the github.com for my case, it will cause the ``git clone''  from github so slow.   And if I use the result given by https://github.com.ipaddress.com/ and set it in /etc/hosts,  the ``git clone'' will faster than using dnsproxy for dns query.

So, I want to let dnsproxy give me the more good results just like this website done. 

Regards
