### ISSUE TITLE
adguard-dns-ipv6 and adguard-dns-family-ipv6 currently unreachable

### ISSUE THREAD

**Issue by jedisct1** [AdguardTeam/dnsproxy#66]
Hi!

Looks like Adguard over DNSCrypt is currently not reachable over IPv6 (but totally fine over IPv4).

Can you take a look?

Thanks!

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardDNS #57](https://github.com/AdguardTeam/AdGuardDNS/issues/57) via [**ZenHub**](https://www.zenhub.com/)
