### ISSUE TITLE
Do not use 0.0.0.0 as response for adblocked domains

### ISSUE THREAD

**Issue by iskradelta** [AdguardTeam/dnsproxy#68]
Let this be a configuration option, which "ip" to return for adblocked domains, or NXERROR.

Example:  node_modules/.bin/dnstls @176.103.130.130 +tls-host=dns.adguard.com  googleads.g.doubleclick.net
"answers": [
    {
      "name": "googleads.g.doubleclick.net",
      "type": "A",
      "ttl": 3274,
      "class": "IN",
      "flush": false,
      "data": "0.0.0.0"
    }

This is a problem, since a client using AdGuard DNS servers above, or Firefox browser on laptop, if vising any shitty webpage or using any shitty application! They could try to connect to services running on Android phone or laptop, just because they have http://googleads.g.doucleblick.net:anyport and basically perform any kind of queries to, supposedly "local" services. This is worse since many developers think running stuff on localhost, or bound to any of their "internal" interfaces is not exposed to the internet.

When using AdGuard DNS, by default, its possible for any program to access services on localhost. 

Specifying an address such as 127.6.6.6 as response, or NXERROR would fix the problem.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardDNS #60](https://github.com/AdguardTeam/AdGuardDNS/issues/60) via [**ZenHub**](https://www.zenhub.com/)
