### ISSUE TITLE
Provide an option to not verify the DNS server certificate

### ISSUE THREAD

**Issue by f4nff** [AdguardTeam/dnsproxy#75]
```
dnsproxy -l 0.0.0.0 -p 5353 -d  -z -u https://cloudflare-dns.com/dns-query 

dnsproxy -l 0.0.0.0 -p 5353 -d  -z -u tls://1.1.1.1:853
```

Can not request parsing.
Isn't openwrt not supported by ssl?
Can I provide an option to not verify the validity of the certificate?

Similar to wget no check certificate

**Comment by rampageX** [comment]
Just install ca-certificates or ca-bundle, and maybe need:

`export SSL_CERT_FILE=/opt/etc/ssl/certs/ca-certificates.crt`

for all golang apps use ssl.

**Comment by f4nff** [comment]
That's too much trouble, I just want to skip the verification certificate with one instruction.

**Comment by natesales** [comment]
Added in #126
