### ISSUE TITLE
[Feature Request] prefetch cached records that are about to expire

### ISSUE THREAD

**Issue by HinderSting** [AdguardTeam/dnsproxy#78]

**Comment by EugeneOne1** [comment]
@BlackLongCock, the optimistic cache is implemented in [v0.38.1](https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.38.1).  Could you please check if it works for you?

**Comment by EugeneOne1** [comment]
@HinderSting, we'll close the issue for now, if you don't mind.  Please feel free to open new issues if you'll face any problems with the current implementation.
