### ISSUE TITLE
Error when linking gomobile framework on iOS

### ISSUE THREAD

**Issue by captainOfM** [AdguardTeam/dnsproxy#87]
I try linking iOS dnsproxy.framework in Xcode 11.3.1 and then get error **Framework not found :dnsproxy**
Where the problem might be?

**Comment by ameshkov** [comment]
Tbh, I don't know. Have you tried building dnssproxy.framework yourself as it's done here:
https://github.com/AdguardTeam/dnsproxy/blob/master/.travis.yml#L123

**Comment by captainOfM** [comment]
yes i build it my self, 
i use 
$ make clean
$ make ios

build was successful and i get dnsproxy.framework, then i try linking with iOS project and xcode show this error, i think so dnsproxy.framework is not compatible with arm64 ios architecture.
 
<img width="847" alt="Screenshot 2020-03-03 at 09 21 52" src="https://user-images.githubusercontent.com/38225240/75752246-01035e00-5d31-11ea-872e-b5c256d47843.png">

**Comment by ameshkov** [comment]
Tbh, I don't know what is the issue.

We were using it in v3.X of AdGuard for iOS, try checking out how it's linked there:
https://github.com/AdguardTeam/AdguardForiOS/tree/v3.1.3

**Comment by captainOfM** [comment]
did you mean AGDnsProxy.xcframework? this one is working because it is xcframework and its supporting arm64 architecture, but i can't build it myself... can i use this AGDnsProxy.xcframework builded framework for my own app ?

**Comment by ameshkov** [comment]
No, I mean `dnsproxy` specifically, it is used in the tag v3.1.3

**Comment by captainOfM** [comment]
Oh ok, i find it at now, and it's builded correct, i can import it to my project, thanks!!.
Last question: AGDnsProxy.xcframework maybe i can use this framework from you newest version ?

**Comment by ameshkov** [comment]
> Last question: AGDnsProxy.xcframework maybe i can use this framework from your newest version ?

This is it:
https://github.com/AdguardTeam/DnsLibs

You can use it, just follow the rules of the GPLv3 license.
