### ISSUE TITLE
How to use it 

### ISSUE THREAD

**Issue by cakexxx** [AdguardTeam/dnsproxy#89]
I run it on my Windows and use the script in the Readme and shows 

> 2020/05/26 22:35:26 [info] Starting the DNS proxy
> 2020/05/26 22:35:26 [info] Upstream 0: tls://dns.adguard.com:853
> 2020/05/26 22:35:26 [info] Starting the DNS proxy server
> 2020/05/26 22:35:26 [info] Creating the UDP server socket
> 2020/05/26 22:35:26 [info] Listening to udp://[::]:53
> 2020/05/26 22:35:26 [info] Creating the TCP server socket
> 2020/05/26 22:35:26 [info] Listening to tcp://[::]:53
> 2020/05/26 22:35:26 [info] Entering the UDP listener loop on [::]:53
> 2020/05/26 22:35:26 [info] Entering the tcp listener loop on [::]:53

Then what should I do?

**Comment by ameshkov** [comment]
Well, yeah, that's right, it works.

It can accept DNS queries and send it the specified upstream DNS
