### ISSUE TITLE
client auth?

### ISSUE THREAD

**Issue by mikedilger** [AdguardTeam/dnsproxy#90]
I love dnsproxy and have been using it to bypass my ISP for a while now like this:(opennic <-> my server unbound <-> my server dnsproxy <-> local raspberry pi dnsproxy <-> pihole <-> my local home network)

Under a new ISP I find myself behind carrier grade NAT amd a frustratingly rotating IPv6 prefix, so I can no longer specify a firewall rule on my server to only allow connections from my home computer.

Is there any way to do client authentication so that only my home server (based on perhaps TLS client side certs or similar) can use my dnsproxy server?

**Comment by ameshkov** [comment]
Hm, well, nothing like that at the moment.

I'd say the most secure way would be to establish an SSH tunnel from your RPi to your server and make your DNS queries go over that tunnel.

**Comment by mikedilger** [comment]
ok thanks.
