### ISSUE TITLE
Does not support HTTP/2

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/dnsproxy#95]
The tested dnsproxy configuration doh/dot does not support http2.0

**Comment by ameshkov** [comment]
It does

**Comment by thb007** [comment]
> It does

When will support be added? This agreement is too old.

**Comment by ameshkov** [comment]
It does support HTTP/2

**Comment by ameshkov** [comment]
Okay, it appears that on your server it does not, thanks for supplying additional info.

**Comment by EntropySmoke** [comment]
I started having the same problem about 2 weeks ago when I connected to AdGuard DoH servers with YogaDNS, which was a DNS intercept driver (for clients, not servers) based on DNSCrypt Proxy. I got this error only on AdGuard DoH (or AdGuard DoH Family or any other AdGuard DoH) servers:
- DNSCrypt log: [DoH-AdGuard-1] does not support HTTP/2.

I used the latest OpenSSL (LibCrypto) Library files (1.1.1.11/1.1.1k) for YogaDNS. What caused this error? Some SSL/TLS agreement/certificate? This error didn't appear to interrupt anything.

**Comment by ameshkov** [comment]
Might be on our side, let me take a look.

**Comment by ameshkov** [comment]
@EntropySmoke should be okay now

**Comment by ameshkov** [comment]
@EntropySmoke my bad, in 30 minutes
