### ISSUE TITLE
panic: qtls.ConnectionState doesn't match

### ISSUE THREAD

**Issue by hongyi-zhao** [AdguardTeam/dnsproxy#99]
Hi,

On Ubuntu 20.04, I compiled the git master version of dnsproxy. When I start it, I meet the following error:

```
 panic: qtls.ConnectionState doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	/home/werner/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.0/unsafe.go:11 +0x245
```
The latest release version doesn't have this problem.

Any hints?

Regards,
HY

**Comment by ameshkov** [comment]
You should build it with vendored dependencies or use `make`: https://github.com/AdguardTeam/dnsproxy/blob/master/Makefile#L18

**Comment by hongyi-zhao** [comment]
```
$ go build -mod=vendor
$ ./dnsproxy -h
panic: qtls.ConnectionState doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	/home/werner/Public/anti-gfw/dns/dnsproxy/dnsproxy.git/vendor/github.com/marten-seemann/qtls-go1-15/unsafe.go:11 +0x245
```

**Comment by ameshkov** [comment]
What version of go do you use?

**Comment by hongyi-zhao** [comment]
```
$ go version
go version devel +e64675a79f Mon Jun 8 22:06:39 2020 +0000 linux/amd64
```

**Comment by ameshkov** [comment]
Well, I am not sure why exactly but these two upstreams seem to not work from your place:

>    --- FAIL: TestUpstreams/https://dns.google/dns-query (5.06s)
>    --- FAIL: TestUpstreams/https://doh.opendns.com/dns-query (1.60s)

Anyways, `go build -mod=vendor` is exactly the command we use to build `dnsproxy` so you may just go with it.

**Comment by hongyi-zhao** [comment]
Ant hints for the following error:
```
2020/09/12 08:42:39 [error] Resolver tls://dns.adguard.com is not eligible to be a bootstrap DNS server
2020/09/12 08:42:39 [error] Resolver https://dns.adguard.com/dns-query is not eligible to be a bootstrap DNS server
2020/09/12 08:42:39 [error] Resolver tcp://dns.adguard.com is not eligible to be a bootstrap DNS server
2020/09/12 08:42:39 [error] Resolver dns.adguard.com is not eligible to be a bootstrap DNS server
```

**Comment by ameshkov** [comment]
Nah, these are expected, there are some tests checking that invalid bootstraps are discarded.
